### ISSUE TITLE
Make an API directory better than list but less technical than the chi docgen version

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#100]

**Comment by raedah** [comment]
Id like a dynamically generated list of API calls available from the web interface, rather then the current api list in the readme which can go out of sync.

**Comment by chappjc** [comment]
Although `/list` is dynamically generated, I'm thinking something with more about parameter semantics

**Comment by ukane-philemon** [comment]
> I'm thinking something with more about parameter semantics 

Can we auto-generate this? I doubt. But we sure can manually add this to the readme.

**Comment by chappjc** [comment]
> But we sure can manually add this to the readme.

This, I think.

Will close this issue.

**Comment by chappjc** [comment]
Maybe what we have here is fine: https://github.com/decred/dcrdata/blob/master/README.md#dcrdata-api
Only thing worth changing IMO is plain language descriptions of the meanings of each endpoint.  Probably not in the table though because it would be too much text for a cell/column.

**Comment by ukane-philemon** [comment]
> This, I think.

Okay, can open an issue to reflect the JTBD. I think those form values accessed in request contexts need to be displayed somewhere as part of the docs.

> Probably not in the table though because it would be too much text for a cell/column.

But, we can add another column? Users can scroll sideways if the view width is small.

**Comment by chappjc** [comment]
>  I think those form values accessed in request contexts need to be displayed somewhere as part of the docs.

To what you you referring?  The path elements like {address}?  Can you give an example from the existing docs?

> But, we can add another column? Users can scroll sideways if the view width is small.

Try it, but Github's Markdown rendering of that will look bad.  However, I think the first column that provides the description is pretty good for most of the endpoints.  If any need additional description, we can give that endpoint a sub-section with complete description.

**Comment by ukane-philemon** [comment]
>To what you you referring? 

This https://github.com/decred/dcrdata/blob/master/cmd/dcrdata/internal/api/insight/apimiddleware.go#L375

**Comment by ukane-philemon** [comment]
>  However, I think the first column that provides the description is pretty good for most of the endpoints. If any need additional description, we can give that endpoint a sub-section after the table with complete description.

Okay, if this comes up we can open an issue to improve it.
