### ISSUE TITLE
chainwork query should order by height instead of time

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1004]
Time does not have to be monotonically increasing with time, but chainwork must be with chain height.

https://github.com/decred/dcrdata/blob/7e7f38e54bb129ca2626669d4b8af2a415d1e005/db/dcrpg/internal/blockstmts.go#L201

**Comment by chappjc** [comment]
@buck54321 Does this seem like a correct change to make?  Asking since I believe you did the chainwork bits.

**Comment by buck54321** [comment]
Should be good. Are we still going to show the data by time on /charts, or do you want to switch to block height there as well?

**Comment by chappjc** [comment]
That's an interesting question because miners can set the time such that block N might have an older date than N-1, which means we probably should not plot by time.  Yet it's preferable to show time/date on the x-axis.  How about plotting work by height, but set the x tick labels with corresponding times?
