### ISSUE TITLE
add block version to /blocks list

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1009]

**Comment by xaur** [comment]
That's useful on individual block page, but wouldn't it be too verbose for blocks list most of the time (except consensus vote times)?

**Comment by buck54321** [comment]
Viewing them collectively gives you a sense of how many nodes have upgraded. Is that the idea?

**Comment by chappjc** [comment]
I think that's the idea.  Although once the upgrade happens (threshold met on the 1000 block rolling window), the info will become far less interesting.

**Comment by xaur** [comment]
If the idea is to give a sense of how many nodes have upgraded then it overlaps with voting.decred.org.

**Comment by raedah** [comment]
Its true it wouldnt always be so useful. Would be useful during an upgrade. In general would also increase awareness that blocks have a version and what the current version is. Its also a very thin field requiring 2 chars width, maybe a bit more to say Version in the header, or could abbreviate to Ver. Regarding the voting website, there is in general a lot of overlap with it and dcrdata and the voting site still leaves a lot to be desired.

**Comment by buck54321** [comment]
We can definitely get the block version in there. Those tables need some attention anyway. Here's the current mobile view.

![image](https://user-images.githubusercontent.com/6109680/53560280-9f068c00-3b11-11e9-8057-e8a115099660.png)


The information on voting.decred.org should also be available through dcrdata. We should also be displaying some distillation on the homepage. Even casual visitors should know that right now a vote has been triggered and voting commences in ~14 days. Some form of the same information could also be displayed at the top of the blocks page, in which case I think we could remove the block version from the table again.

**Comment by xaur** [comment]
> Even casual visitors should know that right now a vote has been triggered and voting commences in ~14 days

This triggered decred/dcrweb#579 as an extra place to remind about CVs.

**Comment by chappjc** [comment]
resolved by https://github.com/decred/dcrdata/pull/1081
