### ISSUE TITLE
add order book / depth chart data to exchange bot and server

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1041]
The aggregated and individual exchange order books would be valuable.

**Comment by s-ben** [comment]
Did anyone else receive this email? Is this spam or interesting? I'm not a dcrdata dev (obviously), but maybe someone else wants to look into this?

![image](https://user-images.githubusercontent.com/1634777/54856937-0b604f80-4cba-11e9-8d4f-688c57a2ae46.png)

Links to this,
https://community.geekforge.io/d/14-block-explorer-for-the-decred-blockchain

**Comment by chappjc** [comment]
Haven't received that.  Note sure if this is of interest to us, but thanks for posting it.
