### ISSUE TITLE
cfg.DcrdServ defaults to wrong port

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdata#1057]
If cfg.DcrdServ is specified with just an IP, it connects to the wrong port.  It should know to use 9109, 19109, etc.. based on what network.

**Comment by chappjc** [comment]
Looks like we only add the port if no DcrdServ is specified at all:

```go
// Set the host names and ports to the default if the user does not specify
	// them.
	if cfg.DcrdServ == "" {
		cfg.DcrdServ = defaultHost + ":" + activeNet.JSONRPCClientPort
	}
```

Needs to use `SplitHostPort` to validate the input.  @dajohi Did you want to fix, or just making the issue?

**Comment by dajohi** [comment]
just making issues as i toy around :)  

dcrd config.go has a func called normalizeAddresses that does the magic.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1087
