### ISSUE TITLE
Integrate data from various time periods

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#106]
Summaries of certain counts such as number of blocks, transactions, etc. could be generated on running time windows (e.g. hourly, daily, weekly, monthly).

the time of each block is in sqlite, so this can be done.

**Comment by xaur** [comment]
I would love it so we could have some montly network health report. Is it possible to also include average ticket price and average hashrate?

**Comment by raedah** [comment]
Related to https://github.com/decred/dcrdata/issues/135
