### ISSUE TITLE
share and protect API Status struct

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1094]
As per the [review discussion](https://github.com/decred/dcrdata/pull/1072#discussion_r261841262), the plan of action is now to unexport the status fields, and make thread safe accessors.  There was already a getter, leaving a needed setter to be implemented.  Finally, sharing the status struct between dcrdata api and insight api is needed.

_Originally posted by @chappjc in https://github.com/decred/dcrdata/pull/1072#issuecomment-469449869_

**Comment by buck54321** [comment]
We still need a struct with exported fields for the `/api/status` endpoint.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1190
