### ISSUE TITLE
Address raw response should return empty array instead of 422

### ISSUE THREAD

**Issue by fernandoabolafio** [decred/dcrdata#1111]
The route `api/address/<address>/raw`  will return 422 (Unprocessable Entity) in two cases:
- Transactions are not found for the provided address.
- The provided address is invalid.

In my opinion, this route should have the same behavior from the non-raw route where the 422 is returned only if an invalid address is provided and if the address is valid but there are no transactions to be listed, an empty array is returned instead.

**Comment by chappjc** [comment]
Agreed.  For raw, it's appropriate to return `[]`, status OK.
