### ISSUE TITLE
Copyright year is still 2018

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdata#1123]
The copyright is still 2018 on the main page (as well as elsewhere in the repo). 

![image](https://user-images.githubusercontent.com/1634777/54096237-41bbd780-4368-11e9-8bfc-5e1afe1e92ec.png)

**Comment by chappjc** [comment]
Thanks for reporting.  These things can slip through the cracks.  However, this has been addressed on master.  See alpha.dcrdata.org for a recent version.
