### ISSUE TITLE
APIs: Block or return empty response for DsQxuVRvS4eaJ42dhQEsCXauMWjvopWgrVg

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1124]
e.g. /api/address/DsQxuVRvS4eaJ42dhQEsCXauMWjvopWgrVg/amountflow/month

**Comment by buck54321** [comment]
[According to a guy I know](https://github.com/decred/dcrdata/issues/358#issuecomment-387182521), those transactions might be interesting.
