### ISSUE TITLE
proposals db: invalid character

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1132]
```
[ERR] DATD: updating proposals db failed: invalid character '<' looking for beginning of value
```

This was a transient error, but there may be a parsing issue we should look into.

**Comment by buck54321** [comment]
Usually this means the API is down and has sent some HTML formatted error page.

**Comment by chappjc** [comment]
Figured it was an html tag starting.  A better error message would be appropriate.  Also, I would think that the http response code would not have been 200 in this case, but we seem to have missed that check.

**Comment by dmigwi** [comment]
I am fixing this but in the future we should consider bypassing the API and fetching all the proposals data from github using the git  command line tool. This could place less strain on politeia API servers.

[Here](https://github.com/dmigwi/go-piparser) is a tool that parses the Politeia's Proposal Votes data stored on github.
