### ISSUE TITLE
Front-end assets build log message

### ISSUE THREAD

**Issue by dmigwi** [decred/dcrdata#1164]
```Shell
removed 'v4'
Building the dcrdata binary...
Packaging static frontend assets...
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-webpack-plugin@0.10.5 requires a peer of stylelint@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 4.497s
```
Do I need to make some changes to my system configuration?

**Comment by chappjc** [comment]
Good questions.  I'm pretty certain the bootstrap warnings aren't important since we're not using bootstrap's JS.  Not sure about the stylelint message though.

**Comment by chappjc** [comment]
I'm almost completely certain there's nothing to worry about with these messages.  We're only using bootstrap's css, not js.  As for the `stylelint-webpack-plugin@0.10.5` warning, package.json specifies `"stylelint": "^10.0.1"`, which seems to be working just fine despite not being considered a "peer" of `stylelint@^8.0.0`.  See https://github.com/webpack-contrib/stylelint-webpack-plugin/issues/174
