### ISSUE TITLE
Modularize api types/api semantics

### ISSUE THREAD

**Issue by matheusd** [decred/dcrdata#1172]
When consuming the dcrdata api from another go project we can directly import the types package. However, as it is currently organized, this implies loading the whole dcrdata project as a module.

Ideally, the api types package should be its own module, with as little external dependencies as possible (hopefully even none).

Bonus points if the api module's version tracked the actual api version, such that (eg) package dcrdata/api would target `api/...` endpoints and breaking changes into the dcrdata api triggered a new module and api endpoint (package dcrdata/api/v2 targetting endpoint `api/v2/...`).

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1197 (among others).

**Comment by chappjc** [comment]
Well, not the api version and endpoint naming, but the go modules are done.  The dep on db/dbtypes will be addressed for 4.1.

**Comment by matheusd** [comment]
Nicely done! Thanks!
