### ISSUE TITLE
Show Total Sent per block

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#122]
Sum of all transactions in the block on the blocks view.

~~Sum of all transactions in the block on the block view.~~ DONE in https://github.com/dcrdata/dcrdata/pull/128

**Comment by raedah** [comment]
This is resource intensive and needs a caching layer before being implemented on the blocks view.

**Comment by chappjc** [comment]
perhaps also mining fees collected in block (spent - sent)

**Comment by raedah** [comment]
ok, ive added the mining fee display to https://github.com/dcrdata/dcrdata/issues/138

**Comment by chappjc** [comment]
@gozart1 is progressing on this

**Comment by chappjc** [comment]
Blocks view now shows total sent in the "DCR" column.
