### ISSUE TITLE
preload high priority web resources

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1221]
`<link rel=preload>` can potentially improve improve page load time if applied to certain resources that should be downloaded as soon as possible.

Notably:

/fonts/icomoon.ttf
/fonts/source-sans-pro-v9-latin-regular.woff
/fonts/inconsolata-v15-latin-regular.woff

**Comment by njirap** [comment]
hallo.

This issue was not auto-closed on PR merge.

It still shows up as open and I bumped into it while searching for my first issue to work on. Maybe stale issues should be closed. Thanks. I will proceed with my search
