### ISSUE TITLE
home: ticket pool size diff from target percentage

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1225]
Instead of

`Ticket Pool Size: 41,285 (100.79% of target 40,960)`

show

`Ticket Pool Size: 41,285 (+0.79% of target 40,960)`

it takes less space, faster to read, and in case of negative number -1% is more useful than 99% (imo)

edit: if there are other places than home page where this is shown, update them too.

**Comment by njirap** [comment]
Hello @xaur 

I have observed this has not yet been actioned.

I would like to take it up.

Thanks

**Comment by xaur** [comment]
Hey @njirap please check with @chappjc to coordinate.

**Comment by njirap** [comment]
ok @xaur 

@chappjc if this is a valid issue I would like to take it up
