### ISSUE TITLE
v4 release notes say "work in progress"

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1237]
https://github.com/decred/dcrdata/releases/tag/v4.0.0

> Summary (work in progress!)

While here, question: are release notes anywhere in the repo?

**Comment by xaur** [comment]
Also, are there release notes for 4.0.1 and 4.0.2?

**Comment by xaur** [comment]
Noticed that the release notes mention 12 contributors while the linked diff shows 11:

https://github.com/decred/dcrdata/compare/v3.1.0...v4.0.0

**Comment by chappjc** [comment]
I just have to finish the release notes.  The notes for 4.0.1 and 4.0.2 are very minor and don't include any user-visible changes.  It's not clear why github says 11 contributors.  I'm getting the summary from `git summary v3.1.0..v4.0.0`, and combining usernames for the same contributor.

**Comment by chappjc** [comment]
I'm afraid we won't get around to this one since 5.2 is coming soon.  :)

**Comment by xaur** [comment]
Haha no big deal. Just wondering if the release notes are stored and versioned in the repo so that someone could contribute to that later?
