### ISSUE TITLE
mempool: show fee rate

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1251]
Add a column to show fee rate for tickets and regular tx.

Sometimes when ticket purchasing is very active it helps to see ticket transactions and their fee rate (I assume fee rate and not just fee is what influences the priority of inclusion in blocks).

This can be a useful indicator for regular tx too.

**Comment by imestin** [comment]
i would like to work on this.

**Comment by chappjc** [comment]
@imestin Great!  You got it.
