### ISSUE TITLE
Add real time mempool viewer

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#129]
Home page currently shows Tickets in Mempool.  
We can also show a count of Transactions in the Mempool.
The word Mempool can be clickable, and go to /mempool , which would be a page that lists all transaction in the mempool and resuses the templates partials for the block view.
getrawmempool rpc should be used.

**Comment by chappjc** [comment]
package mempool needs updating for tracking and reporting tx types other than votes and tickets. (TODO @chappjc)
