### ISSUE TITLE
Unconfirmed transactions are showing unconfirmed inputs.

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#130]
Reproduce by taking a txid from getrawmempool and loading in the dcrdata gui.
The inputs of the unconfirmed transaction show N/A for both the Block Height and Value. 
Then click on the input itself, and see that it included in a block and has a value.

**Comment by raedah** [comment]
This probably has the same cause as https://github.com/dcrdata/dcrdata/issues/142

**Comment by ukane-philemon** [comment]
@chappjc, I think this has been fixed by the merged PRs above, no? Maybe should close if yes.
