### ISSUE TITLE
"apilisten" parameter didn't work in "dcrd.conf"

### ISSUE THREAD

**Issue by Junxin-Huo** [decred/dcrdata#1306]
release v4.1.0

When I want to change the listening address for API.

1. Changing the `apilisten` parameter in in `dcrd.conf` file didn't work with `apilisten=0.0.0.0:7777`.
2. Set the env `DCRDATA_LISTEN_URL` worked.

**Comment by buck54321** [comment]
`apilisten` is a dcrdata configuration setting, so should be set in `dcrdata.conf`, not `dcrd.conf`. Also, the address you tried, `0.0.0.0:7777`, is effectively the default setting, so shouldn't need to be set explicitly. Could you give a little more information about the configuration you are trying to achieve and the unexpected behavior you've encountered?

**Comment by Junxin-Huo** [comment]
Thanks a lot! It's my mistake. When I set apilisten` in `dcrdata.conf`, it works. And the default setting listening address is `localhost:7777`, so I need to change it.
