### ISSUE TITLE
Proposal voting charts - it looks like there are No votes in commits where there were none

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdata#1307]
The issue is quite apparent on the [constitution proposal](https://alpha.dcrdata.org/proposal/amendment-to-decred-constitution-001) - the No votes all happened in a handful of commits, but the presence of small red "bars" all along the x axis makes it difficult to locate the commits where the no votes happened.

**Comment by chappjc** [comment]
I agree that the red bars are too big when they represent 0 votes.  Interestingly, if you use the window tool to zoom in, there is a point where the red bars get reduced to a single pixel row as one would expect, but then zooming out causes them to pop up too much.

**Comment by dmigwi** [comment]
Fixed here https://github.com/decred/dcrdata/pull/1324

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1324
