### ISSUE TITLE
How to use websocket?

### ISSUE THREAD

**Issue by Junxin-Huo** [decred/dcrdata#1308]
release v4.1.0
Hi, I can't connect my `WebSocket` service when I can connect the `REST API` .
How to use WebSocket? May I have a document about WebSocket?

**Comment by chappjc** [comment]
I admit these are questions that should be answered more clearly by the README files.  In short:

- The websocket at the /ws path is strictly for use by the web page.  Connecting to it manually is not supported.
- The websocket at the /ps path is OK for general client use.  See the `pubsub/...` packages for information.  The democlient and psclient packages are there as examples for interacting with the server.  Note that the psclient API is likely to change in the very near future as it is currently hard without creating data races.
