### ISSUE TITLE
admin: add email alerts, and maybe SMS too

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdata#1323]
As system monitoring is added (see #1322), it would be great if there were configuration options to send an email to an administrator when the system state goes downhill. This would require credentials for an SMTP server, but I think most email services have those creds available if you know where to look. 

Additionally, SMS alerts could be enabled via Twilio, though some may understandably object to the use of a commercial product.

**Comment by ukane-philemon** [comment]
@chappjc, What do you think? We could build a separate monitoring tool and would have features like SMTP, Twilio etc. So administrators could effectively get occasional status feedback, there could be an existing tool for this(haven't checked yet) but IDK how we'd want to deal with this.

**Comment by chappjc** [comment]
This kind of monitoring is solved already by many external monitoring tools and services that only need to check on a status endpoint.  There's no need to make a new monitoring tool IMO.
There's software you can run like Prometheus, Monit, etc, and then there are simple monitoring services like UptimeRobot, Checkly, etc.  And most providers offer some basic health check with email and SMS notifications.
I think we should close.

**Comment by ukane-philemon** [comment]
Yeah, we should close.
