### ISSUE TITLE
historic chart of missed tickets per block

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1338]
Having a historic chart of missed tickets would be a useful network health measure and could be used to view an anomalies that occur.

**Comment by buck54321** [comment]
There was some discussion of this at https://github.com/decred/dcrdata/pull/1274#issuecomment-485773848. In short, the data is really boring, and unless something really interesting happens, we're planning to leave that chart in the dust bin. If you are interested in watching for something interesting to happen, the data is now available through `/api/stake/powerless`.

**Comment by chappjc** [comment]
The `"revoked"` array in the response from `/api/stake/powerless` gives everything to visualize the misses over time, should one be so inclined.  If there is an anomaly, it is straightforward to plot the data:

```sh
curl -s https://alpha.dcrdata.org/api/stake/powerless | jq '.revoked|.[].h' | gnuplot -p -e 'plot "<cat"'
```

![image](https://user-images.githubusercontent.com/9373513/58178027-f3df1c00-7c94-11e9-99a1-81ab1551308e.png)

**Comment by chappjc** [comment]
Hmm, well actually "revoked" doesn't tell the story of misses.  @buck54321 would it be crazy to add "misses" to the powerless endpoint?  Possibly a misses array could contain heights, values (as now), plus any revoke height (making the "revoked" array redundant).  What do you think?

**Comment by buck54321** [comment]
So top level sort will be missed/expired, and revocation status will a field alongside height and price. That does seem way better. 

I think the only reason it was sorted by revocation status first was to mimic the chart being dropped.

**Comment by chappjc** [comment]
I'm thinking about miss height vs. revoke height because when a whale staker goes offline, misses will shoot up, but revokes won't change until the whale comes back and revokes them all, probably in one shot.

**Comment by buck54321** [comment]
So is this the idea?

```
{
    "missed" : [
        {
            "price": float,
            "miss_height": int,
            "revoke_height": int || omitempty
        }, 
        ...
    ],
    "expired": [
        {
            "price": float,
            "purchase_height": int,
            "revoke_height": int || omitempty
        },
        ...
    ]
}
```
Maybe abbreviate the field names to keep the size down? Do we want this before 5.0?

**Comment by chappjc** [comment]
There's time, unless there's potential for abuse of this endpoint.

**Comment by chappjc** [comment]
Resolve by https://github.com/decred/dcrdata/pull/1362
