### ISSUE TITLE
Caching, Sum address data

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#134]
Run through the entire set and calculate. Get a count of total transactions. Save that data. Then, next time it runs, be able to just scan the new blocks since the last run and add any new transactions to the total transaction count. Run on each new block received.  Be able to easily rebuild db if needed. Will be useful for all addresses, but primarily used for addresses with more then 2000 txs.

**Comment by chappjc** [comment]
following PR https://github.com/dcrdata/dcrdata/pull/177, the address cache will be added

**Comment by chappjc** [comment]
Resolved by: https://github.com/decred/dcrdata/pull/1109 and https://github.com/decred/dcrdata/pull/1051
