### ISSUE TITLE
Chart of long term data

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#135]
-Ticket price chart
-Ticket pool size (by tickets)
-Ticket pool value (# of tickets * ticket price)
-Percentage of coins staked (ticket pool value / coin supply)
-PoW difficulty chart

**Comment by dmigwi** [comment]
The task title says that a chart for ticket price history `(Ticket pool size (by tickets) history chart)` should be created. The task description also mentions several more types of history charts i.e.

>Coinsupply and stake pool value history chart (can be done in one chart)
>Percentage of staked coins for each block height
>Difficulty history chart
>Hashrate history chart (data source?)

Are this part of the ticket price history chart or they are separate individual charts @raedah

**Comment by raedah** [comment]
Separate charts

**Comment by raedah** [comment]
https://blockchain.info/charts
Blockchain size,
average block size, 
Txns per block, 
median tx confirmation time/fee
unique addresses, 
txns per day

https://blockchain.info/charts/utxo-count
Number of Unspent Transaction Outputs

**Comment by raedah** [comment]
Much of this was taken care of in https://github.com/decred/dcrdata/issues/463 . Keeping open for the few ideas that still remain.
