### ISSUE TITLE
Proposal voting charts - yes no vote totals not updating

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrdata#1356]
Looking at the Journey to future of work prop, the yes and no vote counts at the top are not matching the charts. 
![vote-totals-not-updating](https://user-images.githubusercontent.com/37707106/58425799-b0205400-8092-11e9-9b6b-56bf0de1c99f.PNG)

**Comment by RichardRed0x** [comment]
Just noticed discussion is a likely related bug: https://matrix.to/#/!MgQoetFiyjrHAywokv:decred.org/$15589657213389qGkwY:decred.org?via=decred.org&via=matrix.org&via=zettaport.com

**Comment by dmigwi** [comment]
The issue has been fixed on Politeia's side. Its seems like the Politeia's cache was overwhelmed yesterday by the shear number of bulk No votes cast.

![new](https://user-images.githubusercontent.com/22055953/58428297-b7535c00-80aa-11e9-9d39-728645433fcc.png)

**Comment by chappjc** [comment]
Is this resolved?

**Comment by dmigwi** [comment]
Yes. The issue was fixed on Politiea's end.
