### ISSUE TITLE
proposals try to update during initial sync

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1366]
`[ERR] PSQL: pgb.PiProposalsHistory failed : %v InsertProposal failed: pq: there is no unique or exclusion constraint matching the ON CONFLICT specification`

This is during initial sync, so there are no indexes yet to provide the constraint required by that on conflict specification.

I think Pi updates should not begin until sync is completed.

**Comment by chappjc** [comment]
@dmigwi bump

**Comment by dmigwi** [comment]
Oooh! I forgot about this, Well I will fix it  before the day ends.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1445
