### ISSUE TITLE
dcrdata cannot start if there are no active deployments

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1375]
If `params.Deployments` is an empty or nil map (or `VoteTracker.version` somehow ends up with `0`), dcrdata cannot start.  This is presently the case on simnet, but can happen on any network.

```
[ERR] DATD: Unable to initialize vote tracker: Vote information not found: -32603: stake version 0 does not exist
```

**Comment by chappjc** [comment]
@dmigwi I've assigned @buck54321 to have a look, but some of this code was originally yours I belive.  Please have a look too.  Thanks!

**Comment by chappjc** [comment]
BTW, I think the error message should be supplemented so that it is clear that it is coming from `refreshRCI`.

**Comment by chappjc** [comment]
A general issue I see is that the network params, which includes the Deployments map, is obtained at compile time while `getvoteinfo` makes and RPC request from a node at some other version.  Yet and error with this RPC is fatal.  Something is wrong with the design here I believe.  I'm not sure I understand why it's even necessary to use `params.Deployments` map when everything can come from various node RPCs.

**Comment by buck54321** [comment]
Agree. We should drop the storm db and rework `VoteTracker` to do everything live from the RPC, except historical vote count (which it already knows how to get from dcrpg). Many methods from `AgendaDB` would need to be re-implemented, but its doable. 

I'll get things up and running for simnet first.

**Comment by chappjc** [comment]
The startup issue is resolved by https://github.com/decred/dcrdata/pull/1378, The issue of the compiled in Deployments is now tracked in https://github.com/decred/dcrdata/issues/1376.

**Comment by dmigwi** [comment]
Got to this quite late but all changes made on the PR look good.
