### ISSUE TITLE
proposal page: wrap token

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1391]
When narrowing the view, proposal token overlaps with other fields. Other fields behave nicely. I suggest to wrap the token just like txids and merkle roots are wrapped on the block page.

dcrdata alpha 2019-09-12

![screenshot](https://user-images.githubusercontent.com/24484727/59393013-4928bd80-8d69-11e9-8c2c-f330776f4ea9.png)

**Comment by buck54321** [comment]
Resolved in #1446
