### ISSUE TITLE
proposals list: show voter turnout percentage

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1392]
Currently https://alpha.dcrdata.org/proposals shows absolute vote counts. That number is interesting and must be shown somewhere, but in this table I think 30% would be more interesting than 12369 (for the DEX spec proposal).

**Comment by xaur** [comment]
While there, please right-align that column

**Comment by ReevesAk** [comment]
It is not clear what you want here, could you please make it a bit more descriptive? 

12369 is a number of vote count and presented as whole figure and not percentage

**Comment by xaur** [comment]
The idea is to show `30%` instead of, or in addition to, `12369`. I believe "30% of tickets participated" gives better context than "12369 tickets participated".

**Comment by njirap** [comment]
@xaur I have added the %age.. As for right aligning I think it's already right aligned

**Comment by xaur** [comment]
Cool. Just wondering - is it okay to put calculation code in template files?

**Comment by buck54321** [comment]
Don't want to get too crazy with it, but a simple percent calculation line that is fine.
