### ISSUE TITLE
Green line VISIBILITY - Charts 

### ISSUE THREAD

**Issue by Michae2xl** [decred/dcrdata#1405]
Alpha -> Charts -> VISIBILITY (both selected) -> Week and day filter, the green line maybe disappear 

<img width="1244" alt="charts" src="https://user-images.githubusercontent.com/44928059/59520257-8ab78680-8e97-11e9-8a9d-5a269a5433a5.png">

**Comment by chappjc** [comment]
Thanks for the reports.  This appears to be resolved by a fix in https://github.com/decred/dcrdata/pull/1426

Hopefully we'll have it merged shortly.

![image](https://user-images.githubusercontent.com/9373513/60110487-ae15e780-975b-11e9-85e5-7c5cafe95a62.png)

**Comment by buck54321** [comment]
Resolved by #1426

**Comment by Michae2xl** [comment]
Thanks, Masters!
