### ISSUE TITLE
Recently confirmed transactions do not show recent data

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#142]
On the transaction view, 
Time | Confirmations | Included in block
N/A | Unconfirmed | N/A

**Comment by chappjc** [comment]
Apparently it is expected to not have the transaction input details until the transactions have been validated by votes on the containing block.  Why the `getrawtransaction` is ignorant of the fact that the transaction is in a block already is not clear to me.  I asked about this in #dev on Slack but it's still not clear to me.

**Comment by chappjc** [comment]
Keeping open until upstream fix is available

**Comment by chappjc** [comment]
Upstream fix under review in decred/dcrd#1479. After it is merged, it should be evaluated with dcrdata and changes made as needed.   The dcrd PR is currently running on alpha.dcrdata.org.

**Comment by davecgh** [comment]
I think you mean decred/dcrd#1471.

**Comment by chappjc** [comment]
txns with 1 confirm have correct data for some time now.
