### ISSUE TITLE
scanQueries does not seem to be separating individual queries

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1435]
scanQueries does not seem to be separating individual queries, although this does not seem to be breaking anything, just making it difficult to debug in case of a query/exec failure.

**Comment by dmigwi** [comment]
>does not seem to be separating individual queries

What does it mean? Like all queries are run whether one of them fails or not?

**Comment by chappjc** [comment]
That wasn't very specific - sorry. What I mean was that in this loop, `text` contains the entire contents of the .sql file, not a single query:
https://github.com/decred/dcrdata/blob/f11bfb37ceba8d7844d11a2d72c03966393ce7b0/testutil/dbconfig/config.go#L41
(just a single iteration of the loop does everything)

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1437
