### ISSUE TITLE
Y axis incorrect for tickets staked

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdata#1454]
Decimal needs to be moved one place to the right on the Y axis for "Ticket Pool Value".
https://explorer.dcrdata.org/charts?chart=ticket-pool-value

**Comment by chappjc** [comment]
Thanks for opening an issue.   I believe this is resolved by https://github.com/decred/dcrdata/issues/1454

**Comment by jzbz** [comment]
Ah #1452, missed that, closing.

**Comment by chappjc** [comment]
Hah, thanks for finding the correct link.  :P
