### ISSUE TITLE
align section heights on home page

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1457]
From the comment on reddit by Vadimusnews123

"I propose to increase the number of rows in the tables to align the columns in height."

https://www.reddit.com/r/decred/comments/anu91e/new_decred_block_explorer_by_dcrdataorg/efxtg21/?context=8&depth=9

![5KRrn6I](https://user-images.githubusercontent.com/15878246/60639099-a1a32600-9e10-11e9-9dcf-6cdf160dbcdf.jpg)

**Comment by njirap** [comment]
I'm thinking if the guy has the screenshot (s)he has probably already aligned the columns so (s)he should just PR the code here 😁

Otherwise I can PR it from my end

**Comment by njirap** [comment]
#992
