### ISSUE TITLE
Remove monospace on proposals list

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1461]
I'm not seeing a good reason to use monospace font in the proposals table: https://explorer.dcrdata.org/proposals

iirc it used regular font at some point, but now it is again monospace.

**Comment by xaur** [comment]
Interestingly, I have monospace on one machine and normal font on another.

**Comment by ReevesAk** [comment]
That means it isn't exactly an issue to be fixed?

**Comment by xaur** [comment]
It means that in some circumstances the monospace is still shown and needs to be fixed. Perhaps there is some fallback defined in the CSS?
