### ISSUE TITLE
Amounts are rounded to 6 decimal places on tx pages

### ISSUE THREAD

**Issue by RyanZim** [decred/dcrdata#1486]
DCR amounts are rounded to 6 decimal places on tx pages, despite the fact that DCR has precision to 8 places, and 8 places are displayed everywhere else AFAIK.

For example here: https://explorer.dcrdata.org/tx/ecadccbd7c19ab2fedd6e9c118759df595fda805eb0a69743eda49812171f39c we see `125.239848` for the first output.

![screen](https://user-images.githubusercontent.com/17342435/61998687-9d6dcf80-b081-11e9-8e45-5d8df74b547c.png)

However, on the address page for that output (https://explorer.dcrdata.org/address/DsY1suSrkn8DYnF5BPLvnvSfFbeXTQusUVh), we see the full amount of `125.23984754`.

![screen](https://user-images.githubusercontent.com/17342435/61998708-fb021c00-b081-11e9-8f0f-44c6f615a729.png)

It is extremely confusing to have block explorer rounding the actual amounts on the blockchain. Not to mention the fact that this inconsistency between the tx and address pages makes it even more confusing. Can we get this fixed and display the full 8 places everywhere?

Thanks for the great explorer otherwise, BTW!

**Comment by buck54321** [comment]
I can't believe nobody has noticed this before.

**Comment by chappjc** [comment]
Yeah, Ick.
