### ISSUE TITLE
Fix time remaining time on proposal chart

### ISSUE THREAD

**Issue by s-ben** [decred/dcrdata#1500]
The proposal [Decred Fundamental Metrics Research Proposal - Phase 1](https://alpha.dcrdata.org/proposal/decred-fundamental-metrics-research-proposal-phase-1) just started voting yesterday. However the text below says 'Voting now~1d7h remaining'. I believe this is the time since voting started, not time remaining.

![image](https://user-images.githubusercontent.com/1634777/62182925-306e6a00-b30d-11e9-86f6-2d1c56d10cbb.png)

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1508
