### ISSUE TITLE
circulation chart anomaly

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1504]
Anomaly appears as a series of rapid steps in the line.

![2019-08-06 20 18 19 dcrdata decred org 82635b654c20](https://user-images.githubusercontent.com/15878246/62574185-679dc780-b887-11e9-8b39-1885cad74dc8.png)

Appearing on alpha as well though slightly modified
![2019-08-06 20 19 42 alpha dcrdata org 44500c0b20ac](https://user-images.githubusercontent.com/15878246/62574248-91ef8500-b887-11e9-8eca-1d0caa175255.png)

**Comment by buck54321** [comment]
I think this was resolved by #1560.

**Comment by chappjc** [comment]
Yes, confirmed resolved in https://github.com/decred/dcrdata/pull/1560
