### ISSUE TITLE
Duration between blocks chart on linear scale looks buggy

### ISSUE THREAD

**Issue by zubairzia0** [decred/dcrdata#1522]
The duration between blocks chart looks a bit off since the 6th of Aug :

https://explorer.dcrdata.org/charts?chart=duration-btw-blocks&zoom=ikd7pc00-jzerytc0&scale=linear&bin=day&axis=time

![image](https://user-images.githubusercontent.com/23157945/63226484-025fa580-c1a8-11e9-8469-98599076b1cf.png)

![image](https://user-images.githubusercontent.com/23157945/63226490-199e9300-c1a8-11e9-8a4d-111f3fc32c88.png)

**Comment by chappjc** [comment]
Related: https://github.com/decred/dcrdata/pull/1424
Although the problem in this issue seems to be with the charts cache data.  Needs investigation.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1560
