### ISSUE TITLE
proposal chart no bar hidden

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1526]
For the last displayed hour, the red bar is being hidden off the chart to the right. To resolve this, we likely need to extend the display length of the chart by an hour so all available data is shown.

![2019-08-19 18 04 38 explorer dcrdata org 02d746d69884](https://user-images.githubusercontent.com/15878246/63288309-e2b1a580-c2ab-11e9-8ff6-d2022a83aa8b.png)

**Comment by njirap** [comment]
picking this up..

**Comment by njirap** [comment]
Just to add to this, for the last displayed hour, the green(yes) bar is hidden to the left, I'm still looking into how to fix this, tried adding an extra set of values but the charts get broken...looking into how to fix the length for both the extreme left and extreme right  bars...probably shift it to the lext by one bar
<img width="84" alt="Screen Shot 2019-11-27 at 12 17 29 PM" src="https://user-images.githubusercontent.com/2056512/69710568-b0b4a880-1110-11ea-9d71-d9a104c73988.png">

**Comment by njirap** [comment]
I have fixed this by applying the data padding concept as discussed at https://github.com/novus/nvd3/issues/290

PRing it in a few
