### ISSUE TITLE
Alternate address page viewing type with addresses shown for inputs and outputs

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#153]
@chappjc created the functions needed for this in https://github.com/dcrdata/dcrdata/pull/155

Will need this on Address template as well.

**Comment by chappjc** [comment]
One of the possible views with previous outpoints and their addresses is implemented in https://github.com/dcrdata/dcrdata/pull/155

I propose the view in that PR be the default or only as Sequence and Tree are not very helpful.  They are also in JSON, which is linked to.
