### ISSUE TITLE
Connection to dcrd failed

### ISSUE THREAD

**Issue by Junxin-Huo** [decred/dcrdata#1539]
Connection to dcrd failed: Node JSON-RPC server does not have a compatible API version. Advertises 5.0.0 but requires one of: [6.0.0]

My dcr version: v1.4.0
dcrdata version: v5.1.1

**Comment by Junxin-Huo** [comment]
Is this the version problem? I see the newest version is `v1.4.0` .

**Comment by njirap** [comment]
I'm also unable to start dcrdata but my error is different #1540

**Comment by chappjc** [comment]
Please see the Release Status table: https://github.com/decred/dcrdata/blob/master/README.md#release-status
