### ISSUE TITLE
local dcrdata: `panic: about to connect the wrong block: 376103, 376101`

### ISSUE THREAD

**Issue by njirap** [decred/dcrdata#1540]
I am currently unable to run dcrdata. Attached is the logs. First instance of the error was at `2019-09-02 13:24:22.318` GMT+3

<img width="477" alt="Screen Shot 2019-09-02 at 2 12 28 PM" src="https://user-images.githubusercontent.com/2056512/64110784-b7d74f00-cd8b-11e9-863e-2cd8842bb514.png">

**Comment by chappjc** [comment]
Try to start once with the purge n blocks option.  512 should do

**Comment by njirap** [comment]
ok will try that

**Comment by njirap** [comment]
This works.

Incase anyone else has same issue the command is `dcrdata --purge-n-blocks=512` then subsequent starts can just be `dcrdata`
