### ISSUE TITLE
coinjoin tx chart

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1543]
Scan through the history of transactions and look for ones that match the criteria of having greater than 2 inputs, greater then 2 outputs, and at least 2 outputs of identical dcr amount. Then put it on a chart with block # as the X and # of coinjoin txs as the Y. Could also detect which ones immediately are spent by a ticket to get a comparison on how many are happening through tickets and other. It would be a bit of data to crunch so we would want to precache it.

Would also be useful to take a count of the same amount outputs to rank the size of the coinjoins against eachother. Its better privacy to have less coinjoin transactions taking place, and just have more participants in the transactions.

Another useful perspective could be to show the total amount of DCR joined rather then tx count.

**Comment by chappjc** [comment]
Just out of curiosity, what's the value proposition for this kind of feature?

**Comment by raedah** [comment]
Lots of people are requesting data on privacy usage. Its a starting point and open for collaboration.

**Comment by raedah** [comment]
Per discussion about creating a qualitative measure of privacy, here is one way to do it. Do the partial sum analysis for all transactions in the block. Many of the regular transactions would have a deterministic path, the coinjoins would not. Could then get an avg value of certainty on inputs to outputs for all transactions in the block and weight it by coin amounts. This would provide a general probability measure for how susceptible the chain is to analysis on a block by block basis over time. The previously mentioned quantitative measures a primarily about measuring usage.

**Comment by chappjc** [comment]
There is clearly value in presenting cspp mix data.  Let's make some bullet points in the top post and discuss feasibility here.

**Comment by raedah** [comment]
seems related to https://github.com/decred/dcrdata/issues/1543

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1640, https://github.com/decred/dcrdata/pull/1688, https://github.com/decred/dcrdata/pull/1690, and https://github.com/decred/dcrdata/pull/1720
