### ISSUE TITLE
Redesign treasury

### ISSUE THREAD

**Issue by harlovski** [decred/dcrdata#1552]
current:
![image](https://user-images.githubusercontent.com/47418864/64261566-64a10000-cf35-11e9-8dc3-ebc8e9ec486f.png)

redesign:
![image](https://user-images.githubusercontent.com/47418864/64261381-1d1a7400-cf35-11e9-99f8-84d407a1592f.png)

Tables do not fit on the phone screen, then we use a horizontal scroll.
Min indent between columns in table - 30px.

specs:
https://xd.adobe.com/spec/2cb8634f-c7bc-44ad-48ca-4755cffa64eb-5a89/

**Comment by xaur** [comment]
Let's capitalize Treasury!

**Comment by ukane-philemon** [comment]
@chappjc, Is this redesign still on our radar?

**Comment by chappjc** [comment]
Not like that at least.  That was all before the new treasury anyway.
