### ISSUE TITLE
Issue with Duration between block chart

### ISSUE THREAD

**Issue by ankit-maverick** [decred/dcrdata#1579]
The duration between blocks chart for the last 2 weeks is showing block times close to zero. This issue used to exist after mid-August that I guess got fixed in the recent update for the past dates. The issue still exists for dates after the last update.

<img width="1650" alt="block-duration" src="https://user-images.githubusercontent.com/2875129/66710268-78d8e800-ed92-11e9-9e7d-6b5588f18ed9.png">

**Comment by chappjc** [comment]
Are you seeing this issue running with master?

**Comment by raedah** [comment]
dup of https://github.com/decred/dcrdata/issues/1522 resolved by https://github.com/decred/dcrdata/pull/1560

**Comment by chappjc** [comment]
Yes, it's a dup and resolved.  I'm just trying to make the point that the Issues for this github repo are NOT for the dcrdata website, but rather the source code.

I intend to create an issue template that makes this explicit.
