### ISSUE TITLE
Abandoned status incorrect on /proposals

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdata#1583]
A proposal that is abandoned is marked as "In Discussion" on /proposals.

![image](https://user-images.githubusercontent.com/6109680/67050269-c12f3780-f0fd-11e9-8010-5e56e118ffe9.png)

The proposal is marked appropriately on /proposal

![image](https://user-images.githubusercontent.com/6109680/67050328-df953300-f0fd-11e9-9d3b-2fb0234680f2.png)

**Comment by xaur** [comment]
Still seeing this for https://explorer.dcrdata.org/proposal/amin-rafiee-decred-hackers-congress - the page shows Abandoned correctly but /proposals still shows In Discussion.

**Comment by xaur** [comment]
This affects 3 proposals. On the pic below, only first 2 items are really In Discussion

![proposals-discussion](https://user-images.githubusercontent.com/24484727/73950823-7f1c4280-48f4-11ea-8959-70ad6df03e13.png)

**Comment by mkingori** [comment]
Seems its resolved already.

**Comment by chappjc** [comment]
Confirmed.

**Comment by xaur** [comment]
@chappjc I still experience it on both prod (dcrdata v5.2.2-pre+dev) and alpha (dcrdata v5.3.0-pre+dev).

![polis-prop](https://user-images.githubusercontent.com/24484727/79485472-d598b200-8004-11ea-84ed-282f6738fde3.png)

![polis-props](https://user-images.githubusercontent.com/24484727/79485481-d92c3900-8004-11ea-84da-fa9f808e0fd8.png)

**Comment by mkingori** [comment]
@chappjc I've worked on a fix for proposals showing `In discussion` instead of `Abandoned`
