### ISSUE TITLE
Enable tor hidden service

### ISSUE THREAD

**Issue by peterzen** [decred/dcrdata#1609]
Now that the privacy feature is being rolled out, it would be useful to be have access to `dcrdata` over a tor hidden service.  That way users could configure the `.onion` address in the wallets in order to avoid an accidental leak of their IP address.

**Comment by chappjc** [comment]
http://dcrdata2opeenddl.onion/
Should be featured more prominently, sorry.

**Comment by chappjc** [comment]
That reminds me that I need to deploy 5.2-release there too.  I'll probably shut it down for an upgrade in a couple hours from now.

**Comment by peterzen** [comment]
Awesome, thank you!
