### ISSUE TITLE
Move (UTC) from timestamps to column header or label

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1614]
It would clear up some space if every timestamp didn't repeat the `(UTC)`.

I suggest placing it once in the column header or timestamp's label and removing from all individual timestamps. The users should get used to the general rule that all dates are in UTC.

Pages affected:

- home
- /blocks
- /address
- /agendas
- /proposal
- maybe others

**Comment by xaur** [comment]
@peterzen thanks! One nit: all pages are now pretty except the Latest Mainnet Blocks on the home page. I guess it was missed because when javascript is enabled there is Age column but no Time column. When js is disabled the Time column appears:

![utc-home](https://user-images.githubusercontent.com/24484727/73881049-b3e6b600-4870-11ea-8b45-4acfe20cd9c2.png)

**Comment by peterzen** [comment]
> @peterzen thanks! One nit: all pages are now pretty except the Latest Mainnet Blocks on the home page. I guess it was missed because when javascript is enabled there is Age column but no Time column. When js is disabled the Time column appears:
> 
> ![utc-home](https://user-images.githubusercontent.com/24484727/73881049-b3e6b600-4870-11ea-8b45-4acfe20cd9c2.png)

Thanks for flagging that @xaur, it's fixed now.
