### ISSUE TITLE
/days page, links to individual days are not using correct params

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1619]
All links are going to ?offset=0&rows=20
This is a regression. They used to go to a list of block that offset for the start of that day with the rows being the full number of blocks that occurred on the day.

**Comment by mkingori** [comment]
Picking up on this.

**Comment by LasTshaMAN** [comment]
Is https://explorer.dcrdata.org/days the page mentioned above ?

If I click, say, on [2022-08-14](https://explorer.dcrdata.org/blocks?height=685233&rows=20) it seems I'm getting `height=685233&rows=20` params, 

so height looks OK to me, while rows should probably be changed to reflect the amount of blocks mined on a particular day,

I would maybe like to look into it, if my assessment above is correct.

**Comment by chappjc** [comment]
This issue is resolved.  The point of clicking the day is to go to the blocks for that day, starting with the last block.  I don't think hundreds of rows is desirable.
