### ISSUE TITLE
/agenda page is tallying votes from one extra block

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdata#1621]
https://testnet.dcrdata.org/agenda/fixlnseqlocks

> Voting Start	126768
> Voting End	131808

This seems to indicate that votes are being counted for block 131,808, however this block is actually the start of the next interval and should not be included in the vote tallies.

Relevant discussion on Matrix: https://matrix.to/#/!HEeJkbPRpAqgAwhXWO:decred.org/$157448594549496fBYeg:decred.org?via=decred.org&via=matrix.org&via=pintobyte.com

**Comment by chappjc** [comment]
Thanks, @jholdstock .  Related: https://github.com/decred/dcrdata/issues/1618
@buck54321 Do you think this is in the agenda vote tracker code?  We're both pretty busy right now, but we should try to rectify the vote tracking issues before the mainnet vote gets too far.  I can look into this if you're swamped.

**Comment by buck54321** [comment]
I'm on it.

**Comment by chappjc** [comment]
Nice.  Just at long as one of us is looking into it, no hurry.
