### ISSUE TITLE
pagination selector bugs

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1629]
Pagination on address page is showing the right pagination options but the option for the max possible is greyed out and not selectable.

Pagination on /blocks page (and associated groupings) has several bugs. The years page for example show a drop down when there is only one option and nothing is selectable. The other views often show the options not in numerical order with 10 at the bottom of the list. The blocks page strangely shows a 144 option which does happen to be the length of a window but selecting this would overlap windows.

**Comment by mkingori** [comment]
Working on this.
