### ISSUE TITLE
charts: off-by-one in x-axis

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1643]
At least when in "blocks" binning mode, the block index is off by one (+1).

**Comment by davecgh** [comment]
![image](https://user-images.githubusercontent.com/2115102/71040125-7fb20d00-20eb-11ea-91ff-89610ad521fc.png)

As the following shows, that value is for block 35792, not 35793.
```
$ dcrctl getblockhash 35792 | dcrctl getblockheader - | jq .size
384003
$ dcrctl getblockhash 35793 | dcrctl getblockheader - | jq .size
14825
```

**Comment by chappjc** [comment]
In multiple places: https://github.com/decred/dcrdata/blob/a66e1e66c2a6836044b9161722b43c62864efd0f/public/js/controllers/charts_controller.js#L166

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1507.  However, the block-binned charts no longer show a legend with "Block Height:" but "Date:".

![image](https://user-images.githubusercontent.com/9373513/78826763-b1efbf00-79a7-11ea-8139-d645daad3558.png)

That may not be desirable, but on the current chart, the peak is at 2016/06/10 17:39:27 UTC, which is now [block 35792](https://dcrdata.decred.org/block/0000000000000cbcb8885de289718c071832d78a813b0267abf907f598e2325b) as expected.
