### ISSUE TITLE
Show turnout on the proposal page

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1671]
Voter turnout (% of eligible tickets that voted) is a critical indicator of engagement and is a necessary context for interpreting the Yes percentage. It is now shown on [/proposals](https://explorer.dcrdata.org/proposals) page. I suggest to also show it on the individual [proposal](https://explorer.dcrdata.org/proposal/ditto-communications-proposal-for-decred-phase-3) page too.

**Comment by chappjc** [comment]
Fair point, and a good first issue.

**Comment by mkingori** [comment]
Working on this

**Comment by LasTshaMAN** [comment]
Looks like this has been solved ?

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1706
