### ISSUE TITLE
mempool: always show 8 decimals in fee rate

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1680]
#1655 added fee rate columns to mempool page. I accidentally noticed that small fee rate is displayed in scientific notation instead of the standard 8-decimal notation:

![fee-rate-decimals](https://user-images.githubusercontent.com/24484727/73879099-eb536380-486c-11ea-91f6-8b3ab7ffbd6c.png)

_P.S. it's interesting that someone tries these low fees_

**Comment by xaur** [comment]
Observed on dcrdata v5.3.0-pre+dev.

**Comment by mkingori** [comment]
Can i work on this?

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1704
