### ISSUE TITLE
proposal: odd date format on chart

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1681]
The date format on the chart overlay is not the one used everywhere else, i.e. `YYYY/MM/DD` instead of `YYYY-MM-DD`.

![odd-date-format](https://user-images.githubusercontent.com/24484727/73879660-f3f86980-486d-11ea-9229-e69a5f1046e4.png)

**Comment by xaur** [comment]
The same odd date format is shown on the hashrate chart

![hashrate](https://user-images.githubusercontent.com/24484727/73949232-0d42f980-48f2-11ea-80f6-4cf729a676d5.png)

**Comment by ademuanthony** [comment]
I am working on this
