### ISSUE TITLE
Always show double-digit numbers for non-leading time units

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1682]
The Age column on many pages has an undesired (imo) dynamic where the label size constantly changes between bigger and smaller as the smaller time units alternate between one and two digits:

```
1m 1s
1m 11s
11m 11s
11m 1s
and so on
```

![double-digits-blocks](https://user-images.githubusercontent.com/24484727/73880423-79c8e480-486f-11ea-8a28-3cf59e8093c8.png)

![double-digits-proposals](https://user-images.githubusercontent.com/24484727/73880432-7c2b3e80-486f-11ea-8a84-5c2f62698915.png)

This breaks vertical uniformity that helps our vision to scan the numbers faster, or in other words is annoying.

To address this I suggest one of two approaches:

- always show two digits for all but the major unit (`4h 01m 01s`)
- always show two digits for all units (`04h 01m 01s`)

**Comment by xaur** [comment]
At least these pages are affected: /proposals /blocks /mempool and root (both latest blocks and mempool areas).

dcrdata v5.3.0-pre+dev

**Comment by ademuanthony** [comment]
working on this
