### ISSUE TITLE
sstxcommitment and sstxchange use are not showing on address page

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1685]
expected behavior is to show all occurrences of the use of an address

**Comment by chappjc** [comment]
The sstxcommitment output of a ticket is not even a p2* output but an op_return, so I don't think that's going to happen.

As for sstxchange, those do show up if they are non-zero.  e.g. https://dcrdata.decred.org/address/DskubntgMBbQukHUzfvMaPZkCHsEhfH6Kqx?chart=balance&zoom=ikmx2hs0-in2od280&bin=month  Outputs must be spendable to be included in address results.  Zero-value outputs are by definition not spendable.

**Comment by raedah** [comment]
actually a dup of https://github.com/decred/dcrdata/issues/279
