### ISSUE TITLE
mix chart queries need optimization

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1689]
After observing this running on alpha.dcrdata.org for a while, this needs to be a high priority to fix.  This query and the processing of the result by dcrdata is bogging down the server.

There needs to be a version `SelectMixedVouts` with a height constraint like with `SelectMixedTotalPerBlock`.  Related to the at https://github.com/decred/dcrdata/pull/1640/files#diff-87f7a577b6af45d0284e4c3fbb98ddf5R3685

This change must be done ASAP as this is an expensive query that the server can't afford to have running often.

Ref: https://github.com/decred/dcrdata/pull/1640#discussion_r375321314

**Comment by chappjc** [comment]
@ademuanthony Tracking the issues here.  It does seem to be a show stopper when run on a typical cloud machine.

**Comment by ademuanthony** [comment]
I am working on this
