### ISSUE TITLE
Chart mode parameter gets stripped from the URL and is not applied

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1741]
I open:

https://explorer.dcrdata.org/charts?chart=ticket-price&zoom=k8f3rvwm-k9oqhibz&bin=window&axis=time&visibility=true-false&mode=stepped

it redirects to

https://explorer.dcrdata.org/charts?chart=ticket-price&zoom=k8f3rvwm-k9oqhibz&bin=window&axis=time&visibility=true-false

thus stripping the `mode=stepped` and not applying it on the UI.

explorer.dcrdata.org dcrdata v5.3.0-pre+dev

**Comment by raedah** [comment]
looks like it may be resolved or partially resolved in https://github.com/decred/dcrdata/pull/1765

**Comment by Ekeh** [comment]
This issue has been resolved in #1765

**Comment by ukane-philemon** [comment]
Not fixed. I'll look into this soon.
