### ISSUE TITLE
Short url for treasury "https://explorer.dcrdata.org/treasury"

### ISSUE THREAD

**Issue by linnutee** [decred/dcrdata#1742]
Right now treasury page url is set as the address: `https://explorer.dcrdata.org/address/Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx?txntype=merged_debit`

It would be useful for references (ie. within presentation, speech, etc) to have an easily communicable short url `https://explorer.dcrdata.org/treasury`, similar as it is for `/proposals` `/agendas` etc.

**Comment by ademuanthony** [comment]
I am working on this
