### ISSUE TITLE
Show tx block height on address page. 

### ISSUE THREAD

**Issue by dnldd** [decred/dcrdata#1748]
It'd be great to see the block the tx belongs to on the address page, currently you have to click on the txid to view the "included in block", adding the block height to the list entries would make it easier to scan through txs for an address.

**Comment by ukane-philemon** [comment]
@chappjc, are we having this?

**Comment by chappjc** [comment]
Only if it adds zero computational expenses, and minimal loc changes

**Comment by ukane-philemon** [comment]
okay, will see to it.
