### ISSUE TITLE
Revocation labelled as vote

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdata#1756]
Comparing a missed ticket and expired ticket:

https://testnet.dcrdata.org/tx/11385737d5b5cd651e5e3d348874ff3ae12b26100845149bffa2db16fea91877
https://testnet.dcrdata.org/tx/59c3c36cfecde71513f6d129f9b86f4bc1039466b6957260170931e2e0bf2005

both are revoked, but the link on "Spending Tx" for the missed ticket says "vote" instead of "revocation"

**Comment by ukane-philemon** [comment]
Closed by #1811
