### ISSUE TITLE
Announce onion address in HTTP header

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdata#1770]
Enabling Onion-Location will inform Tor Browser users who hit the plain dcrdata URL that a Tor hidden service is available and provide them the onion address.

https://community.torproject.org/onion-services/advanced/onion-location/

**Comment by chappjc** [comment]
Pretty cool.  We can even build off of commit https://github.com/decred/dcrdata/commit/516d70169cadf8a05290a7262ac63dd3a6fb4eaf to add a `<meta http-equiv="onion-location" content="http://<your-onion-service-address>.onion" />` attribute to the html head element to achieve the same effect without tweaking the reverse proxy.

**Comment by chappjc** [comment]
I hacked it into the header via nginx for now.

![image](https://user-images.githubusercontent.com/9373513/86858280-f7468a00-c085-11ea-98f0-2989c92b1079.png)

**Comment by ukane-philemon** [comment]
@chappjc, is this still relevant? I can add that info in the HTML head.
