### ISSUE TITLE
Feature request: Verify Message

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdata#1771]
https://github.com/decred/dcrd/blob/faec0f8280c67d058ac8ffa2a82d33a13bfa41a3/dcrutil/util.go#L18-L20

I guess this could open a new DoS opportunity on dcrdata, so probably would need some rate limiting.

Decrediton already provides a nice simple UI for this, a text input for each of `Address`, `Signature` and `Message`.

There is also a short piece of explainer text, hidden behind an `i` button:

---

> After you or your counterparty has generated a signature, you can use this form to verify the validity of the signature.  Once you have entered the address, the message and the corresponding signature, you will see VALID if the signature appropriately matches the address and message, otherwise INVALID.

---

![Screenshot from 2020-07-14 10-46-02](https://user-images.githubusercontent.com/6762864/87411192-3eb9a280-c5bf-11ea-8798-5206ec66dae9.png)

**Comment by ukane-philemon** [comment]
@jholdstock is this feature still in request? Would love to get it done.

**Comment by jholdstock** [comment]
I would definitely like to see this feature, I'm not how other people feel though.

**Comment by chappjc** [comment]
Sure.  I suggest starting with the VerifyMessage function, modeled after dcrwallet's.  Then add an API route (POST).  Then a page.
