### ISSUE TITLE
api invalid address checks

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#1779]
https://explorer.dcrdata.org/api/address/sdfdsfdsfdsdjflkjsjkfjlkdsjflksdjflkjdsf/count/5/raw

too many address

https://explorer.dcrdata.org/api/address/sdfdsfdsfdsdjflkjsjkfjlkdsjflkjdsf/count/5/raw

invalid address

Address validity checks only seem to take account of the string length. Passing an address that is invalid but is a long string will result in an incorrect error msg, 'too many address'.

**Comment by ukane-philemon** [comment]
>https://explorer.dcrdata.org/api/address/sdfdsfdsfdsdjflkjsjkfjlkdsjflksdjflkjdsf/count/5/raw

too many address

This now returns `Unprocessable entity`. This new response closes this issue?
