### ISSUE TITLE
New proposal not shown

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1781]
https://proposals.decred.org/proposals/1e55a41 is missing from https://explorer.dcrdata.org/proposals

**Comment by xaur** [comment]
A lot of newer proposals appeared but not the one reported above. I wonder what's so special about it.

**Comment by chappjc** [comment]
Resolved by c7ce753d412740066c8ce045ab598e80ce9df07a

**Comment by xaur** [comment]
The [proposal](https://proposals.decred.org/proposals/1e55a41) in question is now a "legacy" or "archived" one. These are no longer shown on [/proposals](https://explorer.dcrdata.org/proposals) so in a way the bug is no longer reproducible.

But now I miss having a fast-loading list of all proposals via this link:

https://explorer.dcrdata.org/proposals?offset=0&rows=200

@chappjc is there an issue to bring back legacy proposals to dcrdata?

**Comment by chappjc** [comment]
Those are being imported from the old git proposal system to the new tlog system by @thi4go.  When that is done, they will automatically get pulled by dcrdata and show up.  https://github.com/decred/politeia/pull/1477
