### ISSUE TITLE
Proposals Explorer: Bad Request Response

### ISSUE THREAD

**Issue by taoteh1221** [decred/dcrdata#1784]
Choosing how many proposals to show per page on the dcrdata.org website throws an error ( https://explorer.dcrdata.org/proposals?offset=0&rows=30&byvotestatus=all ).

![Screenshot from 2020-10-07 11-38-31](https://user-images.githubusercontent.com/1760489/95354738-c5b2aa00-0892-11eb-9c8e-0d0e27a50a11.png)

![Screenshot from 2020-10-07 11-39-05](https://user-images.githubusercontent.com/1760489/95354758-cea37b80-0892-11eb-9b02-cb6a3bbdb951.png)

**Comment by mkingori** [comment]
Hi. I had worked on this bug and created this [PR](https://github.com/decred/dcrdata/pull/1780).

**Comment by ukane-philemon** [comment]
This must have been fixed by #1838.
