### ISSUE TITLE
Show DEX stats on the Market page

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1786]
The [Market](https://explorer.dcrdata.org/market) dashboard is very helpful to quickly check the state of DCR on most significant DCR markets.

Now that the DEX is running, it already has very nice liquidity/privacy/security/etc so now I care the most about what is happening there.

It would be nice to show DEX stats like price, volume and some handy orderbook overview numbers (like +-2-5% slippage) on the /market page. As a side effect, this will add visibility to dcrdex.

As a small nod to dcrdex's strong fundamentals I would also show a small green checkmark next to dcrdex volume number with a tooltip saying "This volume can be publicly verified from on-chain data". Obviously all other markets will not have this checkmark.

**Comment by degeri** [comment]
I believe @buck54321 is already working on this.

**Comment by xaur** [comment]
So this was mostly implemented by #1789 . I suggest we keep this open until volume is added since it is an important indicator.

Reddit announcement and discussion of the initial dcrdex integration on Markets page [here](https://www.reddit.com/r/decred/comments/joq1j9/block_explorer_dcrdata_markets_page_now_includes/).
