### ISSUE TITLE
Markets: show same number of decimals for all prices

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1790]
DCR rising above 0.001 on dcrdex (congrats everyone) exposed an issue on the Markets page left-hand column. Price values are right-aligned (as they should), but because they have different number of decimal places shown, they are not aligned properly. I had to re-read it like 5 times to realize it is actually 100k sats and not 10k.

The suggested solution is to force all numbers to 6 decimals.

![markets-decimals](https://user-images.githubusercontent.com/24484727/98446343-cb5f1200-2114-11eb-87ad-e06969c83e7b.png)

**Comment by ukane-philemon** [comment]
Price values are now properly aligned. This marks as closed?
Current UI:
![current look](https://user-images.githubusercontent.com/57448127/154300117-5a4ff101-0a19-43f0-91b2-38fee3fb3f9f.PNG)

**Comment by xaur** [comment]
Yeah looks good now. Closing.
