### ISSUE TITLE
return tree with /api/tx endpoint

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1797]

**Comment by ukane-philemon** [comment]
@chappjc, pls can I get more clarification on what this issue is about?

**Comment by chappjc** [comment]
In for example https://dcrdata.decred.org/api/tx/ae42f383a8fe967e17a8c6bb345a08e2016584fdc514e6c1f807645e627955e6?indent=true, a `"tree": 0` or `"tree": "regular"` would indicate if the transaction were in the stake regular tree (vs. stake tree).
