### ISSUE TITLE
"New Block" Web Push notifications not pushing to browser when enabled

### ISSUE THREAD

**Issue by dezryth** [decred/dcrdata#1803]
User not receiving New Block browser notifications after enabling via the "Connected" WebSocket status indicator at bottom of the page.
![image](https://user-images.githubusercontent.com/5300356/107598527-aaaaca80-6be3-11eb-9961-0ecf95427e6d.png)

Tested in a couple browsers:
Firefox 85.0.2
MS Edge 88.0.705.63

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1866
