### ISSUE TITLE
pg=true option in dcrdata.conf file isn't recognized when uncommented 

### ISSUE THREAD

**Issue by dezryth** [decred/dcrdata#1804]
When uncommented in the dcrdata.conf file, running dcrdata intending to use postgresql with "pg=true" in the conf file returns the following:

`dcrdata.conf:53: unknown option: pg`

The following section for PostgreSQL config suggests pg=true needs to be set for the options to be utilized but that does not seem to be the case. These options for recognized for me with `pg=true` commented out.

![image](https://user-images.githubusercontent.com/5300356/107647935-56363800-6c41-11eb-8a14-56013fd78b29.png)

**Comment by chappjc** [comment]
The `pg` switch was removed a while ago because is became a requirement, so I think the resolution is just to remove that from the sample config.

**Comment by chappjc** [comment]
Resolved in https://github.com/decred/dcrdata/pull/1840
