### ISSUE TITLE
upgrade exchange API versions

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdata#1810]
```
https://api.binance.com/api/v1 -> v3
https://bittrex.com/api/v1.1 and v2.0 -> https://api.bittrex.com/v3
```

**Comment by ukane-philemon** [comment]
> @chappjc (on matrix)
I've barely look into the issue, but it would seem the bittrex API?

Can't tell what issue we have with the bittrex API. But all API version upgrade in this issue has been taken care of
