### ISSUE TITLE
Migrate to new politeia API

### ISSUE THREAD

**Issue by lukebp** [decred/dcrdata#1816]
These are the politeiawww enpoints that dcrdata currenlty uses:
- RouteAllVetted
- RouteProposalDetails
- RouteVoteStatus
- RouteAllVoteStatus

These endpoints have been deprecated in the recent politeia [release](https://github.com/decred/politeia/releases/tag/v1.0.0).

Listed below are the routes that should be used instead.  dcrdata currently pulls the politeia git repos manually in order to build the vote graphs.  This is not required anymore.  All data that dcrdata needs should be available through the politeia API.  

The release also includes a politeiawww client to make interacting with the API easier.  This will replace the dcrdata `piclient` package.
[politeiawww client](https://github.com/decred/politeia/blob/master/politeiawww/client/client.go#L164)

The new API uses generic record routes.  A record is application agnostic.  It can be a proposal, a cms invoice, a cms DCC, or any other type of record.  
[Record structure](https://github.com/decred/politeia/blob/master/politeiawww/api/records/v1/v1.go#L219-L230)

**RouteAllVetted**

Replaced by inventory ordered route.

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/records/v1/v1.go#L429-L441)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/records.go#L149)

**RouteProposalDetails**

Replaced by record details route. 

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/records/v1/v1.go#L306-L316)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/records.go#L80)
[pictl reference cmd](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdproposaldetails.go)

Here's a function that converts a record to a proposal from the legacy `www/v1` API.  This shows how proposal data is formatted in the generic record structure.
https://github.com/decred/politeia/blob/master/politeiawww/proposals.go#L863

**RouteVoteStatus and RouteAllVoteStatus**

Replaced by ticket vote summaries route.

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/ticketvote/v1/v1.go#L515-L534)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/ticketvote.go#L126)
[pictl reference cmd](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdvotesummaries.go)

**Cast vote data**

The cast vote replies now contain the vote timestamp so that the dcrdata vote graphs can be built using the API data.

[req/reply payloads](https://github.com/decred/politeia/blob/master/politeiawww/api/ticketvote/v1/v1.go#L453-L476)
[client method](https://github.com/decred/politeia/blob/master/politeiawww/client/ticketvote.go#L109)
[pictl reference cmd](https://github.com/decred/politeia/blob/master/politeiawww/cmd/pictl/cmdvoteresults.go)

Feel free to ping me if you have any questions.

**Comment by thi4go** [comment]
Will be working on this 👍

**Comment by chappjc** [comment]
Great, @thi4go!  Glad to have you tackle this.

**Comment by chappjc** [comment]
Thanks, @lukebp.  I am *very* please that we don't need to get vote history from either git or a tlog backend directly.

**Comment by chappjc** [comment]
Oh, and a related issue is getting the final snapshot of Pi data from the old API and storing it somewhere pre-parsed.  That can probably be separate work though... depends on the changes.
