### ISSUE TITLE
OpenGraph tags

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrdata#1822]
There are no OpenGraph tags in the dcrdata HTML, which means that links shared on social media do not have any image, logo or description.

The following tools can be used to preview how shared links will appear on Twitter and Facebook.

https://cards-dev.twitter.com/validator
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fexplorer.dcrdata.org%2F

Compare with the [preview of dex.decred.org](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdex.decred.org) to see the potential improvement.

I haven't opened a PR for this myself because the image tags require absolute URLs, and I'm unsure how to access the current site URL in `extras.tmpl` - all of the resource URLs in there are relative.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1870
