### ISSUE TITLE
Proposal discussion link broken

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1823]
https://explorer.dcrdata.org/proposal/politeia-pi-2021-q3-proposal-system-

has a `Discussion` link pointing to

https://proposals.decred.org/proposals/91cfcc8c62af2022

but it doesn't open. The correct link is

https://proposals.decred.org/record/91cfcc8

Possibly part of #1816 but this issue is about a specific bug reproducible on the main site.

**Comment by chappjc** [comment]
The main site is in 6.0 release now.  Resolved (aside from legacy proposals being absent)?

**Comment by xaur** [comment]
Yeah links work now. I'm also seeing that each proposal row is duplicated but that's a separate issue. Closing this, thanks.

**Comment by chappjc** [comment]
Seeing that too.  That's new, yay.
