### ISSUE TITLE
Treasury link gone from the home page

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1830]
Not sure if it was removed intentionally, but there was a Treasury block on the home page in the Distribution section (bottom-right). With some refreshing and private tabs I got it to appear once or twice but I cannot reliably reproduce it.

![dcrdata-no-treasury](https://user-images.githubusercontent.com/24484727/120943904-3ad7c700-c721-11eb-8d71-91a2e22804ea.png)

**Comment by chappjc** [comment]
This was an unintended consequence of disabling pre-fetch of the old project fund balance on the deployments.  Will re-enable this option in production over the next day or two.
Thanks for bringing this to my attention.
