### ISSUE TITLE
Expose more treasury mechanics on tspend tx page

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1835]
Currently the [tspend tx page](https://explorer.dcrdata.org/tx/c322f3f93c8aa6d75846ea8ca1d7c9228d23bdef6c21413f8101e7922f265735) shows voting block interval and Yes/No vote counts. These numbers alone do not directly say if the tspend is likely to be approved or rejected. To help with that, as well as the general education, let's expose more stuff from the [DCP-0006](https://github.com/decred/dcps/blob/master/dcp-0006/dcp-0006.mediawiki):

- max possible votes for the interval
- min required votes
- approx. calendar dates of start and end blocks (because we love humans)
- quorum pass progress
- Yes threshold pass progress
- show which Pi key signed the tspend
- show if tspend amount passes or violates the policy (TEW and TEP params)
- anything else?

A side bonus is that when people will screenshot and post this info on social media, it will educate everyone and expose the non-trivial and cool bits like the limits on the burn rate.

**Comment by ukane-philemon** [comment]
@xaur I am currently working on this. Anything else?

**Comment by xaur** [comment]
Not me. You can double check in #dcrdata chat room I guess.
