### ISSUE TITLE
Latest mainnet blocks show 0 for all columns if dcrd disconnects

### ISSUE THREAD

**Issue by monsa00** [decred/dcrdata#1846]
It appears that if the dcrd rpc host disconnects dcrdata does not fully recover unless it's restarted. The logs will show an error:

` [WRN] JAPI: updateNodeConnections: failed to get connection count: the client has been shutdown`

The dcrd logs show that dcrdata does reconnect, and dcrdata doesn't show any major error other than the above. 

This is what shows until dcrdata is restarted:

<img width="821" alt="Screen Shot 2021-08-02 at 2 04 27 PM" src="https://user-images.githubusercontent.com/66281245/127931326-e2076152-d9f0-4a80-b6ae-31cb76624cc2.png">

**Comment by chappjc** [comment]
> For the zero blocks display, I think we can/should display some information from the db, right?

Maybe.  It could be a lot of code and queries since we just use RPCs for many such things. Really does not seem worth it since the dcrdata needs to be restarted anyway.

**Comment by ukane-philemon** [comment]
> Maybe. It could be a lot of code and queries since we just use RPCs for many such things. Really does not seem worth it since the dcrdata needs to be restarted anyway.

Well since dcrdata is handicapped without dcrd there is nothing to do about this for now. Maybe this can close?
