### ISSUE TITLE
stakedb: eliminate badger

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#1856]
In the `stakedb` package, there's a "pool diffs" db that is used to help get the ticket pool at any height.  At each block it has tickets in (+) / tickets out (-).

It's kept in memory after loading it, and while dcrdata is running, it just appends new diffs as blocks are connected.
The other db operation is just on dcrdata startup when it loads _all_ the diffs.

The diff serialization is simple and well defined, and it is a very simple data set, so a custom file format should be used instead of a general purpose DB like badger.

**Comment by ukane-philemon** [comment]
@chappjc what do you think is a nice replacement for badger, boltDB?

**Comment by chappjc** [comment]
Let's pause this issue for now.  Changing the encoding solved it for the most part.
Bolt is actually quite terrible
