### ISSUE TITLE
Abandoned proposal shown as Vote pending

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#1884]
dcrdata shows an Abandoned [proposal](https://proposals.decred.org/record/a3fa55f) as "Vote pending"

![dcrdata-vote-pending](https://user-images.githubusercontent.com/24484727/145666124-74cca731-3741-4c6b-948c-78891cc780f1.png)

**Comment by amass01** [comment]
@chappjc may I investigate this one ?
