### ISSUE TITLE
Reminder that dcrd master no longer supports the address index.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrdata#1921]
As a reminder, the address index (`--addrindex`) has been removed from dcrd master and thus will be removed in the next release, so `dcrdata` will need to be updated accordingly.

I believe the only part of `dcrdata` that still uses the address index from dcrd is the insight API.  However, all of this information is now available via `dcrdata`'s own postgres tables.

**Comment by chappjc** [comment]
Thanks for the reminder.  This will be resolved by https://github.com/decred/dcrdata/issues/1768.  I should swing back on that soon.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1876 I mean
