### ISSUE TITLE
ui: unused info icon 

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrdata#1939]
I see unused icons(hovering or clicking does nothing) on the following pages, `/blocks`, `/ticketpricewindows` , `/years`, `/months`, `/weeks` and `/days` and am thinking they shouldn't be there since they are of no use? or am I missing anything?

some of these icons where added in https://github.com/decred/dcrdata/pull/1509 but I think there should be a message since there is an info icon.

<img width="186" alt="Screenshot 2022-12-05 at 7 52 34 PM" src="https://user-images.githubusercontent.com/57448127/205719171-e1282447-f9c8-40fc-a205-27d1ceef4dea.png">
<img width="202" alt="Screenshot 2022-12-05 at 7 52 58 PM" src="https://user-images.githubusercontent.com/57448127/205719242-b2a8e148-2929-473e-9b06-5fb4acbee3b6.png">

**Comment by chappjc** [comment]
Agree that they serve no purpose without any tooltips.  I can't imagine what needs to be said "Blocks", but "Windows" could use something to briefly explain the stake diff window to which this refers.

**Comment by ukane-philemon** [comment]
Maybe we should display a brief message about the page for all pages with that icon?
