### ISSUE TITLE
помогите пожалуйста с выводом монет из за ошибки блокчейн

### ISSUE THREAD

**Issue by AlexBur8042322** [decred/dcrdata#1955]
здравствуйте разработчики! Я не могу вывести свои монетки DCR с леджер, поддержка леджер не может мне помочь.
ID транзакции:  e1ee3b4481a7b035305d0d6293ae3283b1627f696fa32818c878e20e92b68210
ID транзакции:   47223aab95994a13896a84d8e12a23e4bdc81426ba96e00fc3f996609d9ddf3d
в этих транзакциях есть ошибка. помогите   исправить ошибку

**Comment by ukane-philemon** [comment]
Эти транзакции были созданы более 11 месяцев назад. Почему тебе нужна помощь с ними прямо сейчас?
