### ISSUE TITLE
помогите ! проверьте возможность ошибки

### ISSUE THREAD

**Issue by AlexBur8042322** [decred/dcrdata#1956]
мой адрес DCR:   DsdHymL18DrSdKc5mJXtAJq8T33TBP6znrq
на него поступили средства:   ID транзакции:  47223aab95994a13896a84d8e12a23e4bdc81426ba96e00fc3f996609d9ddf3d
![photo_2023-02-21_22-04-03](https://user-images.githubusercontent.com/125199519/220436008-9f6d416f-24f8-4de9-9049-86ce09619338.jpg)
![photo_2023-02-21_22-04-31](https://user-images.githubusercontent.com/125199519/220436170-77c7f0a7-67a8-4400-81ea-831b71a6a9e3.jpg)
не могу вывести средства! леджер новый, приложения все работают, эта сумма не выводит.
![photo_2023-02-21_22-07-47](https://user-images.githubusercontent.com/125199519/220436686-9f97070b-78b0-4d63-876f-c7025a131255.jpg)

https://user-images.githubusercontent.com/125199519/220438530-e9cf4568-87aa-4267-b051-508e1ea537c6.mp4

**Comment by AlexBur8042322** [comment]
please help me! check the error

**Comment by chappjc** [comment]
Contact Ledger support.
You may also come to the support channel at chat.decred.org

Not related to dcrdata, so closing the issue.
