### ISSUE TITLE
Remove `/stats` page

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrdata#2000]
https://dcrdata.org/stats is still in the Stone Age. I want to redesign and implement the new design for the /stats page but I want to be clear about if that's what we want for the project or if we want to retire the page completely considering that some of those stats are on the homepage.

<img width="1509" alt="Screenshot 2024-07-23 at 12 56 04 AM" src="https://github.com/user-attachments/assets/f2acc813-0511-43f0-a96e-c011e4523f2c">

cc: @chappjc

**Comment by ukane-philemon** [comment]
It turns out we don't want a redesign of this page. I suggest removing it entirely from dcrdata. Any thoughts @chappjc  @davecgh

**Comment by davecgh** [comment]
I'm fine with it being removed.  It doesn't match the style of the rest of the site and I don't find it particularly helpful either.  All of the information is available on the main page in a nicer format, imo.
