### ISSUE TITLE
Vote agenda pages

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#210]
Specification:
-Top level issues page shows a list of all issueids.
-Clicking on an issueid goes to a page for that issue, with issue description and choice descriptions.
-Store locally past issueids that have been removed from dcrd for historical reference.
-Show start and end date for voting period.
-Show vote count totals.
-Show vote result. pass, fail.

**Comment by chappjc** [comment]
Either the new DB, which uses pg, or a more lightweight solution could be used to store the old agendas.  For instance: https://github.com/decred/hardforkdemo/pull/78

**Comment by raedah** [comment]
Examples of agenda can be seen on the following votes,
lnfeatures
http://explorer.dcrdata.org/tx/a8338993728dfb7b65a5c3c97b45b75a4252c88a92e088b24515c45a4411fe37
sdiffalgorithm
lnsupport
http://explorer.dcrdata.org/tx/d31f52ecb6ffbec60544bf5fd79efb62b04465db3df5c36fcf79f146c0a21dea

**Comment by raedah** [comment]
closed by https://github.com/decred/dcrdata/issues/523
