### ISSUE TITLE
Trends page

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#259]
Perhaps with a menu item next to "Explore" there could be a "Trends" link to a page with charts of certain data over time.  Such as what @gozart1 made here: http://dcr-data.netlify.com/#/proof-of-stake

**Comment by raedah** [comment]
related https://github.com/dcrdata/dcrdata/issues/135

**Comment by raedah** [comment]
Charts of data over time were addressed by https://github.com/decred/dcrdata/pull/463
