### ISSUE TITLE
Implement the Insight API

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#260]
For compatibility with many platforms that use it.

**Comment by alexlyp** [comment]
After discussing with @behindtext, we've decided to abandon insight/insight-api altogether in favor of dcrdata along with an the insight-api endpoints implemented.  I will begin discussion of this transition here.  

First step to the process will be do audit all the insight-api endpoints that our various services use (copay/exodus).  I've reached out to the Exodus team and will post their required endpoints here.  I'll research bitcore-wallet-service for it's needed endpoints so copay keeps working.

**Comment by alexlyp** [comment]
From Exodus:
- broadcast tx
- `/tx/${txId}` -- for transaction confirmation
- `/addrs/${addresses}/utxo?noCache=1` -- fetch UTXOs for importing private key and wallet startup
- `/addrs/txs` -- fetch tx data on wallet refreshing
- also we use socket.io for incoming transactions

**Comment by chappjc** [comment]
Completion and testing of HTTP endpoints is being tracked in Issue #400

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/644
