### ISSUE TITLE
Add real time ticket pool viewer

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#278]
A page with a list of all tickets in the ticket pool. Each item is clickable to see the creating transaction.
Summary at the top shows totals, such as ticket count, total dcr amount, median avg dcr amount, median avg age.

**Comment by chappjc** [comment]
This is "In Progress" on the project board, but I do not believe it is being addressed presently.  The [ticket pool PR](https://github.com/decred/dcrdata/pull/542) by @dmigwi was different.

**Comment by raedah** [comment]
The description for this issue, though quite different, ended up evolving into the Ticket Pool Chart as the best way to represent it since there was no easy way to get 40960 items onto most pages. Additional ways of representing the ticket pool could come as a new issue in the future, so will close this.
