### ISSUE TITLE
explorer: Difference with insight explorer

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#284]
Accidently noticed this address looks different in two explorers:

https://mainnet.decred.org/address/Dsc5cgj8jWkCaTxjKcx989j4AHWcAKvEkyt
https://explorer.dcrdata.org/explorer/address/Dsc5cgj8jWkCaTxjKcx989j4AHWcAKvEkyt

All totals differ: number of transactions, total received, total spent and total unspent.

Which one is showing correct data?

**Comment by chappjc** [comment]
Insight has this:


Unconfirmed Txs Balance | -33896.85755258 DCR
-- | --
No. Transactions | 79

This seems to be already included in dcrdata's numbers

**Comment by xaur** [comment]
Adding unconfirmed balance gets it closer, but some difference still remains. Perhaps the difference lies in 42 transactions not included by dcrdata?

counter|Insight|dcrdata|diff
-------|-------|-------|----
received|16278684.71109571|16316764.48752568|38079.77642997
spent|16008036.79157628|16116806.51773640|108769.72616012
unspent|270647.91951943|199957.96978928|-70689.94973015
tx count|25353|25392|39
unconfirmed|-33830.57597948
count of ^|81

**Comment by chappjc** [comment]
Note that in dcrdata's table caption (e.g. `funding transactions 1 — 20 of 25,712`), the count is referring to the number of transactions that pay to the address.  I'd prefer if we can break the confusing precedent of a "from address" and transactions that spend "from an address" as this distorts how the transaction ledger works.  Instead, I'm good with talking about spending the coins of a specific outpoint, for which the previous/funding transaction of that outpoint pays to a certain address.

This seems subtle, but it helps explain why I've made the address page the way it is.  The table goes through transactions that pay to the address, but as a bonus it will show other transactions that spend one of the outpoints.  Perhaps the layout and styling needs to be reworked to reflect this better.  Also, it's reasonable to show the total transaction count, which is the number of funding txns + number of txns that spend those coins.  The later count is not displayed anywhere.

**Comment by xaur** [comment]
I just noticed dcrdata's tx page explicitly shows outpoints, while insight shows addresses (but has outpoints in tooltip and in the link).

The "from address" issue you are referring to is probably the one described at https://en.bitcoin.it/wiki/From_address

Sorry I haven't wrapped my head around that yet, but even with my limited understanding of it, it seems reasonable to ask:

* Which explorer's numbers are more accurate?
* Is insight showing wrong numbers?

**Comment by ukane-philemon** [comment]
> Accidently noticed this address looks different in two explorers:
> 
> https://mainnet.decred.org/address/Dsc5cgj8jWkCaTxjKcx989j4AHWcAKvEkyt https://explorer.dcrdata.org/explorer/address/Dsc5cgj8jWkCaTxjKcx989j4AHWcAKvEkyt
> 
> All totals differ: number of transactions, total received, total spent and total unspent.
> 
> Which one is showing correct data?

@chappjc, As of now these two pages seem to have the same data. Or is there anything am missing?

**Comment by chappjc** [comment]
It was a glitch that was resolved long ago with DB fixes.
