### ISSUE TITLE
Blocks page: Older and Newer links require javascript

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#297]
At the [blocks page](https://explorer.dcrdata.org/explorer) the "Older" and "Newer" navigation links do not work if javascript is disabled. If enabled, they work and send to URL with proper parameters e.g. https://explorer.dcrdata.org/explorer?height=193934&rows=20 . Such URLs work with javascript disabled, so it seems possible to serve Older and Newer links in plain HTML.

**Comment by chappjc** [comment]
resolved by PR https://github.com/decred/dcrdata/pull/476
