### ISSUE TITLE
On the search not found pages, use websockets to refresh when the item becomes available

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#307]

**Comment by ukane-philemon** [comment]
@chappjc, Is this still an issue? I only see one need for this which is a search for future blocks where the server returns an `ExpStatusFutureBlock` error and the time to the future block displayed. IMO, trying to check every x sec to make the item available via ws is overkill unless there is something am missing.  

If the item ain't available the user can check another time (they won't even be on the same search page AFAICT).
