### ISSUE TITLE
Unconfirmed transaction display

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#309]
TYPE and MATURE are out of alignment.
INCLUDED IN BLOCK is missing. Instead of being removed entirely, can say 'mempool'.

**Comment by chappjc** [comment]
hmm, and MATURE says "true"

**Comment by idris92** [comment]
I will be working on that

**Comment by chappjc** [comment]
The `MATURE: "true"` thing was resolved in PR https://github.com/decred/dcrdata/pull/520.

"TYPE" and "MATURE" line up, but we still need "INCLUDED IN BLOCK" to be there with "mempool" instead of a block number.
