### ISSUE TITLE
Cleanup error msg page

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#313]
Example
https://explorer.dcrdata.org/tx/cc5ca5a9c51261ff9a4120f911aef2552a49f9230f829eb9dd9cb39fb1b47f0e

We dont need to say Error. Lets just say what happened. The transaction could not be found. Cleanup design.

**Comment by chappjc** [comment]
resolved by PR https://github.com/decred/dcrdata/pull/484.  @raedah , confirmed?
