### ISSUE TITLE
Ticket Pool Size from the explorer block not the same as that of the api block summary

### ISSUE THREAD

**Issue by oluwandabira** [decred/dcrdata#314]
But it is the same for the api block verbose endpoint. The api summary gets its info from the sqlitedb while both the explorer and api verbose endpoint get theirs from the rpc. The api summary seems the give the ticket pool value of the next block sometimes and that suggests an bug with the db query.

**Comment by chappjc** [comment]
I believe the data from sqlite (originally from stakedb accounting) is correct... but so is the RPC data.  The issue is that the ticket pool stats from RPC do not reflect the tip block.  I recall discussing this with @davecgh at some point.  I'll have to look into that.

As for what to do...

**Comment by chappjc** [comment]
Yeah, `GetBlockVerboseByHash` returns block data that includes the ticket pool size *before* that block got mined.  But if you did `livetickets` after that block was mined, you would find the pool size could be different.

So, the verbose endpoint (/api/block/best/verbose) that calls that RPC is fine given the interpretation of that data structure I've described.

The explorer on the other hand, this could be confusing to the user.  The pool size there has the same meaning as the RPC result but it's presented in such a way that you would expect the pool size *given the transactions mined in that block*.  The explorer page should query sqlite for this information instead.

**Comment by davecgh** [comment]
The value in the header, which is what `GeBlockVerboseByHash` returns, can't be changed as that would invalidate the block.

**Comment by chappjc** [comment]
Perhaps we accept the differences and address this with different terminology.  For instance, "confirmed live ticket pool" vs. "tip live ticket pool".

**Comment by ukane-philemon** [comment]
@chappjc, is this still an issue?

**Comment by chappjc** [comment]
Non-issue.  The JSON data for a block header is what it is.  The home page (and the /api/stake/pool response) will show ticket pool size that reflects the best block even if the best block's header doesn't reflect itself.
