### ISSUE TITLE
Drop support for sqlite

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#321]
Migrate all parts of the code base that use sqllite over to using direct RPC calls, or into full mode (postgres). Request for comments on any part of the code base that this would be problematic with. As far as I know, its mostly the dcrdata api interface that uses sqllite, and this would be a good candidate to be in full mode with postgres.

**Comment by chappjc** [comment]
You'd lose support for historical ticket fee info, ticket pool value/size, and some other stuff.  Anyway, I think we can replace sqlite with storm for anything we want persistent and also available in lite mode.

**Comment by chappjc** [comment]
FYI, I'm referring to https://github.com/asdine/storm, which is a layer on [Bolt](https://github.com/coreos/bbolt)

**Comment by chappjc** [comment]
We've switched to badger instead of storm for the ticket pool DB, for loading performance reasons.  If we ever decide to replace SQLite with a pure Go implementation (of any DB), badger might be worth trying.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1480
