### ISSUE TITLE
Load web server before building the db

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#352]
Lets load the web server when launching the application, instead of waiting till after the database is built which can take a long time. We can display any message, status of the db building, or allow the interface to be used with available data.

**Comment by chappjc** [comment]
It would be nice to have the profiler up too

**Comment by influx6** [comment]
Am currently taking a go at this issue on my fork. See commit [a1d740ad6d153f3a6bb3f7505ea79f9a60ea3519](https://github.com/influx6/dcrdata/commit/a1d740ad6d153f3a6bb3f7505ea79f9a60ea3519). Although am able to use the http explorer api, i do wish to ask if there is away to deal with the estimator. See log below:

```2018-03-19 15:12:10.989 [WRN] BLKD: estimatestakediff is broken:  -32603: stake difficulty estimation does not currently work when the retarget interval is larger than the ticket maturity (interval 144, ticket maturity 16)
2018-03-19 15:12:11.016 [INF] BLKD: Unable to find block (0000000000bdeddd751ec946d6b2792b1e13d346dc02978ed1a2613524b8f303) in pool info cache, trying best block.
2018-03-19 15:13:01.602 [WRN] BLKD: Collected block height 78996 != stake db height 33872. Pool info will not match the rest of this block's data.
```

A you can see my changes, bring about a few issues with the estimator, my question are the ff:

1. Does this affect the way the httpapi shows and calculates the transactions being processed and loaded by the blockchain?

2. Will the issue be resolved once the full transaction has being resolved, so there would be no reason to worry on the estimator error above?

Any clearity would be great on this.

**Comment by dmigwi** [comment]
Awesome stuff

**Comment by dmigwi** [comment]
https://github.com/decred/dcrdata/issues/356, https://github.com/decred/dcrdata/issues/399 Relate to what this task will do.

On task completion a sync status page will be introduced which is the only page that can be loaded when the background sync is in progress... Of course, a progress bar will be added on the new sync status page.

A configurable option will be added to the`dcrdata.conf` file that shows how many blocks back will it take to display the status page ONLY on the running web server. By default it will be set to 2 and we could allow user to increase the value to maybe 5,000 blocks behind.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/710
