### ISSUE TITLE
Page size selector should only display valid options

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#360]
The page selector on the address page will show Page Size options for 20, 100, 1000 items per page. It shows this when only 15 rows are being returns.  
If 15 rows are being returned, then the page size selector should now be shown. 
If 47 rows were being returned, page size options should be 20, 47.  (47 is the max rows available)
If 522 rows were being returned, page size options should be 20, 100, 522.
If over 1000 items are being returned, then show 20, 100, 1000. (1000 is the max allowed rows displayed)

**Comment by raedah** [comment]
The selector should default to the currently selected choice.

**Comment by chappjc** [comment]
Resolved by PR #411
