### ISSUE TITLE
Make api directory tree navigable

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#362]
Currently going to  https://explorer.dcrdata.org/api/ in the browser returns an error page. Instead it can show clickable links to the end points available in for the api. This can be created as a view, or more ideally, dynamically generated from available end points.

**Comment by chappjc** [comment]
/api/list is close.  We can make the links clickable

**Comment by chappjc** [comment]
/api by itself could be forwarded to /api/list, but I since most of the endpoints require parameters, I don't know how practical it is to make the endpoints clickable.

**Comment by chappjc** [comment]
Since few endpoints work without sensible arguments, and the /list endpoint already exists, I'm closing the issue.  If there are specific endpoints that would be good to have browseable, this can be reopened.
