### ISSUE TITLE
Please add support for appdata and ~ for all files/dirs and use sane defaults

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrdata#363]
Currently, dcrdata directories violate the element of least surprise and it litters the filesystem if you launch it the wrong directory.

We need dcrdata to be able to be run without any command line switches and have it default to an expected data directory. It is ok to bomb if templates are missing or a config is missing; just print a message to the user to copy needed files/directories to the expected directory.

Do use the same semantics as dcrd and use the same directory structure as well. For example, the sqlite db file should end up in something like ~/.dcrdata/data/mainnet/dcrdata.sqlt.db

**Comment by RogueElement** [comment]
I think this should be closed.
