### ISSUE TITLE
Show page for blocks in the future

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#372]
Instead of an error, for any block numbers that are ahead of the current height, display a page which says the block is not available yet. It will be available in x many blocks, which is approximately x days, hours, min away. Use websocket to automatically show page when block is available.

**Comment by SeaLightHouse** [comment]
I am doing this .

**Comment by jemacom** [comment]
@SeaLightHouse any help needed ?

**Comment by SeaLightHouse** [comment]
I have raised the pr https://github.com/decred/dcrdata/pull/653
Will close by today or tomorrow

**Comment by SeaLightHouse** [comment]
Ok I see .

**Comment by SeaLightHouse** [comment]
I will implement that too.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/769
