### ISSUE TITLE
Generate histogram of transactions over time on address view

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#378]
Histogram chart range would be from oldest transaction to newest transaction.
Could show by transaction count, or by transaction value.
Highlight different transaction types in different colors.

**Comment by dmigwi** [comment]
Since this chart looks more of historical data I will add it to the charts page.
Here are the specific transaction types that I will consider for the histogram Vote(SSTx), Ticket (SSGen), RegularTx and RevokeTx (SSRTx).

**Comment by raedah** [comment]
It would be on the address page itself, only applying to transactions for the specific address.

**Comment by chappjc** [comment]
resolved by https://github.com/decred/dcrdata/pull/597
