### ISSUE TITLE
turbolinks dropping url params

### ISSUE THREAD

**Issue by gozart1** [decred/dcrdata#408]
When clicking "next" in the address table, query params such as "?n=20&start=80" get dropped after the page loads.

Looks like the cause might be the "Turbolinks-Location" header which is related to redirects
https://github.com/turbolinks/turbolinks#following-redirects

So maybe including the limit and offset params here where the header gets set will prevent the params getting dropped. https://github.com/decred/dcrdata/blob/master/explorer/explorerroutes.go#L392

**Comment by raedah** [comment]
related https://github.com/decred/dcrdata/issues/376

**Comment by chappjc** [comment]
The issues w/ this on the address page are addressed in PR #385.  The same fix described in the description may be applied to the other pages too.
