### ISSUE TITLE
Dcrpg: all networks use the same database

### ISSUE THREAD

**Issue by RogueElement** [decred/dcrdata#414]
Currently all networks use the same default pg database, dcrdata and this will cause problems if checking out another network.

**Comment by codemaestro64** [comment]
Can this be fixed by prefixing table names with current network within same database？

**Comment by chappjc** [comment]
It could, but keeping the tables separate would make backup/restore much easier when just doing one network.  Also, changing the table names would unfortunately require a ton of edits.

Simply changing the default database to `dcrdata_{netname}` would be preferable.

**Comment by ZeroASIC** [comment]
Well that was messy, I apologize for that.  I thought I had screwed something up (I actually made a white space mistake and deleted the commit only to redo it a few minutes later) but it looks like the master branch is a bit busted.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/862, although it is not the case by default that a dynamic DB name will be used.
