### ISSUE TITLE
dcrd must be run with optional indexes to work with dcrdata

### ISSUE THREAD

**Issue by mikefullman** [decred/dcrdata#420]
By default (sample conf) dcrd does not enable optional indexes.  Initial sync of dcrdata throws tons of:

> [ERR] SKDB: Unable to get transaction 609...d9ae: -32603: The transaction index must be enabled to query the blockchain (specify --txindex)

To fix this dcrd.conf needs:  

```
txindex=1
addrindex=1
```

I have not validated yet if one or both are required.  It would be good to mention this in the dcrdata readme.  I can do a PR.

**Comment by chappjc** [comment]
A PR for the README would be welcome.
