### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#423]
On the current https://beta.dcrdata.org/ the options box at the top right is flying way off to the right, looks like it was suppose to be aligned next to the search bar though. Having it on the far right is strange on a wide screen monitor.

At https://beta.dcrdata.org/block/000000000000000526926958a320be6b5a12761236356467e49b28c9f5eb362f  where it says "No missed votes in this block." there is an underline where there shouldnt be.

Change the color of the green progress bars to something that matches the color scheme.

**Comment by chappjc** [comment]
It would also be good to be able to close the menu with either the Escape key or clicking off the menu.  Now it's just the X.

Regarding the underline below "No missed votes..."  I think this is an improvement as the text on its own looks a little funny.  Perhaps it doesn't need to be a line all the way across, but I think it needs something to punctuate it.
