### ISSUE TITLE
Percentage of blocks/tickets found within given time

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#438]
Expose expected and actual percentage of blocks found within given time. Example below via davecgh.

Expected:
10 sec: 3.28%
30 sec: 9.52%
1 min: 18.13%
2 min: 32.97%
3 min: 45.12%
4 min: 55.07%
5 min: 63.21%
6 min: 69.88%
7 min: 75.34%
10 min: 86.47%
20 min: 98.17%
30 min: 99.75%

Actual:
10s: 2.30%
30s: 8.46%
1m0s: 17.81%
2m0s: 33.42%
3m0s: 45.53%
4m0s: 55.58%
5m0s: 63.74%
6m0s: 70.38%
7m0s: 75.74%
10m0s: 86.72%
20m0s: 98.09%
30m0s: 99.70%

**Comment by raedah** [comment]
Grouping this together since they are similar.
* measure the percentage of tickets found within a given time, show compared to the statistical ideal value.
* measure the expiration rate of tickets, show compared to the statistical ideal value.

**Comment by HamzaAnis** [comment]
Hey.

**Comment by HamzaAnis** [comment]
https://tlk.io/dcrdata
Can you please come here. I want to discuss about this issue.

**Comment by HamzaAnis** [comment]
What's you work space name?
I need to speak to readha.

**Comment by ukane-philemon** [comment]
@chappjc, is this still an issue?

**Comment by ukane-philemon** [comment]
I think this should close, If another request for this comes up we can reopen.
