### ISSUE TITLE
Return spent status for output of tx (in the api)

### ISSUE THREAD

**Issue by matheusd** [decred/dcrdata#441]
#110 solved the problem of showing the spent status of outputs on the UI.

It would be helpful if the same was done for the api now (either return a boolean indicating if the output was spent and/or the txid/vin where it was).

**Comment by chappjc** [comment]
Agreed.  Should be fairly easy now that PR #432 made the full DB accessible to the API.

**Comment by chappjc** [comment]
resolved by PR https://github.com/decred/dcrdata/pull/704
