### ISSUE TITLE
Create graphical block display

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#453]
Per the mockup at https://github.com/decred/dcrdata/issues/451
Also include the upcoming block (mempool) and show it being built in real time.
This is probably a good item for @gozart1

**Comment by denyszayets** [comment]
How is this upcoming block built is displayed currently?

**Comment by raedah** [comment]
Upcoming block data is currently being shown at http://explorer.dcrdata.org/mempool , in the same form that blocks are displayed such as http://explorer.dcrdata.org/block/234151

**Comment by chappjc** [comment]
In progress in https://github.com/decred/dcrdata/pull/660 by @dmigwi
