### ISSUE TITLE
Tx view, link to spending tx when spent true.

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#459]
If Spent is True, then True should be a link to the tx that spent it.

**Comment by chappjc** [comment]
Can you identify a case where that's not happening correctly?

**Comment by raedah** [comment]
https://testnet.dcrdata.org/tx/df858ce172d176c274c51bc4229f1b58c1bc20006a1c69639f3173de51faf88b

**Comment by chappjc** [comment]
Ah, testnet was still running in lite mode since the MIT thing, where these links are not possible.  I think we can close this unless there are other cases lingering.  It is catching up now.
