### ISSUE TITLE
Disable keyboard navigation indicator by default

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#473]
Beta site is showing the large blue link selector box on all pages. Im a fan of keyboard navigation, but this shouldnt be being displayed to all users by default. It also does not operate well with using the up and down buttons on the keyboard for page scrolling.

The box should not appear until the user first taps a navigation key.

**Comment by chappjc** [comment]
Hmm yeah the scrolling thing is an issue.  Perhaps just left and right can move around. And a box with much thinner be lines can used, and it should probably disappear after a few seconds

**Comment by gozart1** [comment]
That PR was still wip, finishing touches incoming.

**Comment by gozart1** [comment]
closing since this has been address in https://github.com/decred/dcrdata/commit/645a285e8b94781d07bc314613dfbb52f486ff35
