### ISSUE TITLE
Suggest Descriptor Change on Main Site

### ISSUE THREAD

**Issue by oregonisaac** [decred/dcrdata#488]
I suggest embedding a small image (perhaps like a logo) and a basic descriptor with more info such as "powered by" or similar statements.  A sort of "light branding" just reminding what the site does.

Currently when you look in Telegram at the site homepage for example the preview is:
-----------------------------------------
Decred Block Explorer by dcrdata.org
dcrdata web
-----------------------------------------

it could be cool if this description just had a tiny bit of info - like "XXXXX based engine reading the Decred blockchain" and a small image (like a logo) for dcrdata

**Comment by chappjc** [comment]
@oregonisaac Like this? https://github.com/decred/dcrdata/pull/517

**Comment by chappjc** [comment]
resolved by https://github.com/decred/dcrdata/pull/517
