### ISSUE TITLE
Support getCoinSupply API

### ISSUE THREAD

**Issue by dajohi** [decred/dcrdata#502]
https://explorer.dcrdata.org/api/status?q=getCoinSupply

needs to match

https://mainnet.decred.org/api/status?q=getCoinSupply

**Comment by chappjc** [comment]
The insight API is on a separate path prefix, although that endpoint doesn't seem to be implemented.  Well have to add that to the list.
@papacarp, do you recall the status Insight endpoint

**Comment by alexlyp** [comment]
Yah this was added on top of the insight ones so CMC could pull it.

**Comment by papacarp** [comment]
Insight does not have a coin supply endpoint.  Looks like its here however:  

https://explorer.dcrdata.org/api/supply

Do we want this on top of the insight status endpoint or on the /api status endpoint? (or both)

**Comment by chappjc** [comment]
We don't want to change /api/status since that's dcrdata's own API.  @alexlyp Did CMC request it that `q=getCoinSupply` bit?  Very recently someone from one of those sites requested a supply endpoint from dcrdata, which I added, mainly for them.  Can whoever just use the new one?

**Comment by alexlyp** [comment]
No I believe it was just our decision to use those sematics. 

We could just use the new and then redirect when they use the old to the proper api URL.

**Comment by chappjc** [comment]
CMC is now using dcrdata /api/supply endpoint.  Closing as there is no longer a need to implement the ad hoc `status?q=getCoinSupply` endpoing that was added to the Insight explorer.
