### ISSUE TITLE
Immature ticket not showing ETA

### ISSUE THREAD

**Issue by JFixby** [decred/dcrdata#511]
[Current master](https://github.com/decred/dcrdata/commit/69bf97b12b3808797f21c53e53fa9c33364bbb7e). 

To reproduce:

1) Open any immature ticket
2) See MATURITY status
```Immature, eligible to vote in 134 blocks (0.0 days remaining)```
Expected: `0.5 days remaining`

![image](https://user-images.githubusercontent.com/1580663/41789900-1f04fe4a-7651-11e8-9737-de22b99b21f1.png)

**Comment by JFixby** [comment]
Seems like a misplaced bracket.

https://github.com/decred/dcrdata/blob/master/explorer/explorerroutes.go#L212
https://github.com/decred/dcrdata/blob/master/explorer/explorerroutes.go#L310

**Comment by chappjc** [comment]
Regarding POOL STATUS, it's not a misplaced bracket as the ticket spend status cannot be obtained unless in full mode.  It's not available in lite mode.  The proper fix is to not show this row in html.

Regarding the MATURITY progress bar, yes it should say the days.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/525
