### ISSUE TITLE
views: missing ticket pool status

### ISSUE THREAD

**Issue by JFixby** [decred/dcrdata#518]
https://explorer.dcrdata.org/tx/189c29b8ec4c5ef27adee31d5c0d6473e1109225fe7dcf2b6374708f5d945663

![image](https://user-images.githubusercontent.com/1580663/42027952-3df4ead0-7acb-11e8-90d4-dfd69c3b792f.png)

```

TYPE | Ticket
-- | --
POOL STATUS | /
MATURE | True
LUCK | 0.0000 final, (Best: 0 Avg: 0)

```

Should be smth like:

![image](https://user-images.githubusercontent.com/1580663/42027976-53424e78-7acb-11e8-8a10-c9e021fea216.png)

**Comment by JFixby** [comment]
# dcrdaat log:

```
2018-06-28 12:09:48.717 [INF] SQLT: Invalid address 189c29b8ec4c5ef27adee31d5c0d6473e1109225fe7dcf2b6374708f5d945663: decoded address is of unknown format: invalid format: version and/or checksum bytes missing
2018-06-28 12:09:52.482 [ERR] SQLT: Unable to get block height for hash 189c29b8ec4c5ef27adee31d5c0d6473e1109225fe7dcf2b6374708f5d945663: sql: no rows in result set
```

**Comment by chappjc** [comment]
That log isn't important.  You got there with the search bar, and that's just what happens while it tries to figure out what you sent it.  It really shouldn't be `ERR`

**Comment by chappjc** [comment]
The relevant log entry on the live explorer is `[ERR] EXPR: Unable to retrieve ticket spend and pool status for 189c29b8ec4c5ef27adee31d5c0d6473e1109225fe7dcf2b6374708f5d945663: sql: no rows in result set`.

I don't know why, but it's probably an error with reorg and PostgreSQL handling.

**Comment by chappjc** [comment]
resolved
