### ISSUE TITLE
Window list view

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#538]
/windows, similar to the /blocks , but with data grouped by window number (groups of 144 blocks on mainnet). Rows will list data useful for windows, such as sdiff, total tickets purchased, total transactions. The window # will be clickable and go to a page.. either /window/x  or  /blocks?height=x&rows=144 that shows the block for that window.  On the /blocks view, we will want to add a column specifying the window number.

Similar views can also be added for block groupings of  /days   /months   /years

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/750
