### ISSUE TITLE
missing ticket info UI elements

### ISSUE THREAD

**Issue by JFixby** [decred/dcrdata#557]
Testing current master revealed some missing ticket info UI elements.

Expected:

https://explorer.dcrdata.org/tx/19625aea3252d5beb05c12e7df0079786e585ba4ef10207bce159f402f3d6818

![image](https://user-images.githubusercontent.com/1580663/42996852-18551a4c-8c15-11e8-8c61-2885bd865695.png)

Actual:

http://localhost:8080/tx/19625aea3252d5beb05c12e7df0079786e585ba4ef10207bce159f402f3d6818

![image](https://user-images.githubusercontent.com/1580663/42996825-04335eac-8c15-11e8-86f5-f7345be9c347.png)

**Comment by chappjc** [comment]
Issue resolve by https://github.com/decred/dcrdata/pull/558 on master and 2.1.  See https://beta.dcrdata.org/tx/9dfdd5bbe2fa402bbfdc7008e44d093b8d183792edd93ee97f3b4dbe22765059

**Comment by JFixby** [comment]
Seems lie it is not: https://explorer.dcrdata.org/tx/736d0790deaaca27a9363c21c6c285c249ff73d7222a8ddc7048dbaeaf8dab09
