### ISSUE TITLE
unknown ticket ... spent in block

### ISSUE THREAD

**Issue by JFixby** [decred/dcrdata#575]
This error randomly occurs killing the `dcrdata`.

Log:

```
...
2018-07-27 12:13:18.239 [INF] SQLT: resyncDBWithPoolValue() completed in 1m59.2488589s
2018-07-27 12:13:18.239 [INF] DATD: SQLite sync ended at height 4095
2018-07-27 12:13:18.239 [INF] DATD: PostgreSQL sync ended at height -1
2018-07-27 12:13:18.239 [ERR] DATD: dcrsqlite.SyncDBAsync failed at height 4095.
2018-07-27 12:13:18.239 [INF] EXPR: Stopping mempool monitor
2018-07-27 12:13:18.239 [INF] EXPR: Stopping websocket hub.
2018-07-27 12:13:18.239 [ERR] EXPR: Do not send on stopPing channel, only close it.
2018-07-27 12:13:18.771 [INF] DATD: Closing connection to dcrd.
2018-07-27 12:13:18.771 [INF] DATD: Bye!
2018-07-27 12:13:19.032 [ERR] DATD: unknown ticket a10547a4bcb59914e85d747a1acb971f2f989b9a0600ec5c4d60d6a58a679dc8 spent in block
```

**Comment by chappjc** [comment]
There are some easy ways to accidentally misconfigure dcrdata (or rebuilddb2) to get that error:

These are:

1. the data directory (`datadir`) has data for the wrong network
2. you forgot `--testnet` and it's using mainnet params for a testnet `datadir`
3. you are connecting to a testnet/mainnet node with with the (opposite) mainnet/testnet switch

I don't think there is an unknown bug, but rather a need to check things to prevent the above.

**Comment by chappjc** [comment]
Code from @JFixby: https://github.com/decred/dcrdata/compare/master...JFixby:utsib

**Comment by JFixby** [comment]
Happening here: https://github.com/decred/dcrdata/blob/master/db/dcrsqlite/sync.go#L88

**Comment by JFixby** [comment]
Test reproducing the issue: https://github.com/decred/dcrdata/commit/b750e60b3cca688ae5ec9efe4673147ecf179c34

**Comment by JFixby** [comment]
The test reproduces behavior of the `stakedb.go/ConnectBlock()` function: 
https://github.com/decred/dcrdata/blob/2614a4e3c0e65120f3746672e8cbfe6d15469d5d/stakedb/stakedb.go#L481
at
https://github.com/decred/dcrdata/blob/2614a4e3c0e65120f3746672e8cbfe6d15469d5d/stakedb/stakedb.go#L512

**Comment by JFixby** [comment]
Full code: https://github.com/decred/dcrdata/compare/master...JFixby:reproduce_575

**Comment by chappjc** [comment]
That does not reproduce it.  It just shows that the downloaded db file is corrupted.  Reproduce means operation that leads to such a corrupt db.

**Comment by JFixby** [comment]
This test doesn't have a db file. There are only block files produced by storing ```block.Bytes()```.

**Comment by chappjc** [comment]
The reason why this issue is annoying to me is that I don't see a way to repro it with the product.  Why don't we hit the bug by syncing regularly?  Start fresh, deleted data folder, no errors

**Comment by JFixby** [comment]
There are two scenarios to have the issue: 
(1) Misconfigure dcrdata as you mentioned above. Happens sometimes, hard to reproduce, easy to fix by cleaning cache.
(2) Call the [`block.Bytes()`](https://github.com/decred/dcrdata/compare/master...JFixby:utsib). Unnecessary call, more like a sanity check. Gets the error regularly. Fix is unknown yet.

**Comment by chappjc** [comment]
I'm trying to understand (2).  If you add a call to block.Bytes() like you did in ConnectBlock, does the error happen when doing a regular sync with stock dcrdata?

**Comment by JFixby** [comment]
This is how I reproduce it:
1) checkout master
2) add `block.Bytes()`
3) sync from scratch
Fails at the 4096 block - I guess this is first one to vote.

**Comment by chappjc** [comment]
To see what's different when block.Bytes is in there, you can run the sync with some log statements.

Right before `err := db.connectBlock(`, print the number of maturing, voted, and revoked tickets, and winners.

Then before `db.applyDiff`, dump info about `poolDiff`.

Then near the end you can dump `pib`.

Do this for regular sync that works, then again with `block.Bytes()` in there that breaks something.
