### ISSUE TITLE
merged debit view - cannot switch back to all tx

### ISSUE THREAD

**Issue by papacarp** [decred/dcrdata#579]
Issue with PR #524 
steps to replicate:

1.  view this address:  http://127.0.0.1:7777/address/DsiJmwqFbsCEc1H3HF8UeRjoqJtKt9ZFRKw
2.  change to merged debit view
![image](https://user-images.githubusercontent.com/11194546/43358989-836c9928-924f-11e8-8160-9bcf60bbd0d5.png)

3.  change back to ALL view (or debit/credit)
![image](https://user-images.githubusercontent.com/11194546/43358995-995ca66a-924f-11e8-82e8-30ba51ce0158.png)

The problem:  N is getting set to 1 on merged debits and not reset back to 20

**Comment by dmigwi** [comment]
Fixed by this commit https://github.com/decred/dcrdata/pull/570/commits/c9dcabdafec5156250ababb931aa9faa87bd16f6 in #570
