### ISSUE TITLE
Icons implementation for the new Design

### ISSUE THREAD

**Issue by denyszayets** [decred/dcrdata#586]
Connected
![connected](https://user-images.githubusercontent.com/33739891/43585664-b028b856-9633-11e8-9633-1ef03fcc3605.png)
![connected 2x](https://user-images.githubusercontent.com/33739891/43585665-b037dd40-9633-11e8-8f3a-99de83616bf9.png)

Disconnected
![disconnected](https://user-images.githubusercontent.com/33739891/43585678-b60349c6-9633-11e8-85f0-d740157cfccf.png)
![disconnected 2x](https://user-images.githubusercontent.com/33739891/43585679-b619d736-9633-11e8-93db-41e36a44cf1d.png)

General
![general](https://user-images.githubusercontent.com/33739891/43585680-b640d264-9633-11e8-9d72-fa3a28b89f51.png)
![general 2x](https://user-images.githubusercontent.com/33739891/43585681-b64ef876-9633-11e8-868d-3d5beebf279f.png)

Logo
![logo](https://user-images.githubusercontent.com/33739891/43585682-b6608168-9633-11e8-9b7f-b5a3972d25bb.png)
![logo 2x](https://user-images.githubusercontent.com/33739891/43585683-b66fafee-9633-11e8-8594-03c325a595c6.png)

Menu
![menu](https://user-images.githubusercontent.com/33739891/43585685-b69e236a-9633-11e8-9ea0-5a7594030701.png)
![menu 2x](https://user-images.githubusercontent.com/33739891/43585686-b6aed854-9633-11e8-85bf-232f02db2245.png)

Mining
![mining](https://user-images.githubusercontent.com/33739891/43585687-b6be996a-9633-11e8-9ce1-54632a457c97.png)
![mining 2x](https://user-images.githubusercontent.com/33739891/43585688-b6e34d82-9633-11e8-99f6-02dc72a25168.png)

Stacking
![staking](https://user-images.githubusercontent.com/33739891/43585689-b6f3a72c-9633-11e8-9601-11d20c6edbe1.png)
![staking 2x](https://user-images.githubusercontent.com/33739891/43585690-b7047ae8-9633-11e8-8079-d390c8ef93a9.png)

Swap Currency
![swap](https://user-images.githubusercontent.com/33739891/43585691-b7139b72-9633-11e8-8cb8-c53755ede0cc.png)
![swap 2x](https://user-images.githubusercontent.com/33739891/43585692-b724c104-9633-11e8-9dba-6c7f13a81b70.png)

Icons: [icons-dcrdata.zip](https://github.com/decred/dcrdata/files/2253601/icons-dcrdata.zip)
@raedah @tarun1475

**Comment by denyszayets** [comment]
@dmigwi please see attached ;)
1x
![votes](https://user-images.githubusercontent.com/33739891/44958229-58f6a580-aeab-11e8-86ac-6f4d4983d007.png)
2x
![votes 2x](https://user-images.githubusercontent.com/33739891/44958230-5b58ff80-aeab-11e8-8ceb-6b00fb65bab0.png)

1x
![amount](https://user-images.githubusercontent.com/33739891/44958231-5eec8680-aeab-11e8-9e19-966e267b073f.png)
2x
![amount 2x](https://user-images.githubusercontent.com/33739891/44958232-601db380-aeab-11e8-997c-9d0abbd528d2.png)

**Comment by dmigwi** [comment]
@denyszayets How about this?
<img width="98" alt="screen shot 2018-09-03 at 17 36 44" src="https://user-images.githubusercontent.com/22055953/44992487-fe8b4100-af9f-11e8-9659-bf7010b31eca.png">

**Comment by denyszayets** [comment]
Sorry my friend! You didn't mention Ticket I excluded it.

![ticket](https://user-images.githubusercontent.com/33739891/44992566-9586d780-af65-11e8-952b-95218eb17917.png)
![ticket 2x](https://user-images.githubusercontent.com/33739891/44992567-9586d780-af65-11e8-891b-e6c40e2b2f9c.png)

**Comment by dmigwi** [comment]
Thanks.
