### ISSUE TITLE
agendas page: show message when no agendas

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#588]
It just shows an empty table right now @ https://testnet-beta.dcrdata.org/agendas.  Looks like an error.

**Comment by raedah** [comment]
Column headers should be removed and a msg put in place that says,
"No agendas found for networkname."

You can get the networkname in the same way that the https://testnet-beta.dcrdata.org/parameters page does.

The message should follow the same formatting as the ticket section here.
http://explorer.dcrdata.org/block/265438
