### ISSUE TITLE
API endpoint for block rewards

### ISSUE THREAD

**Issue by prasadraje** [decred/dcrdata#590]
Propose a new endpoint to the REST API to return current block rewards

path = /rewards
alternately, you could put it as a sub-path of the best block because the values are current as of the best block
path = /block/best/rewards

returns the current values of the block reward and pow, pos, dev components. Also include the current block so if someone stores these values away, they would know later that these were valid for the given block number.

Example output:

{
"block":262167,
"block_reward":20.53992222,
"pow_reward" :12.32395335,
"pos_reward":6.1697665,
"dev_reward":2.05399222
}

**Comment by chappjc** [comment]
resolved by https://github.com/decred/dcrdata/pull/592
