### ISSUE TITLE
Detect alternate address formats in search

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#618]
If a testnet address is detected in the search box for mainnet, we could display a message "You pasted a testnet address, you can find it here." with a link redirecting the user to the testnet dcrdata instance page with their address information, and vice versa.

If a bitcoin address is pasted, we could display the message with a link to a bitcoin block explorer.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/846
