### ISSUE TITLE
Tag releases in semver format

### ISSUE THREAD

**Issue by jrick** [decred/dcrdata#623]
It would be helpful for developers importing dcrdata packages and wishing to use module builds to publish releases in semver format (vMajor.Minor.Patch).  Modules are built in (but feature-gated) in Go 1.11, and can used with a Go 1.10 toolchain with vgo (a drop-in replacement for the go tool).

When a module is first imported or is updated to the latest version, and if any semver tags exist on the repo, the version chosen is the maximum semver tag.  Currently for dcrdata, this is v1.3.2.  However, beginning with major version 2, tags have the form v2.0, v2.1, etc.  These tags are not recognized by a module-aware Go and are discarded from the version solution.

By tagging all v2.x releases with semver names (v2.0 can also be tagged as v2.0.0, and v2.1 as v2.1.0), these tags will be recognized by a module-aware Go, freeing developers from needing to track the master branch (which is described as version v0.0.0-date-sha1, and is lower in the total ordering of versions than any published version).

You do not have to switch to module builds to do this, even past the first v2 release.  The go tool recognizes that v2 and higher versions existed prior to the existence of modules, Minimum Version Selection, and Semantic Import Versioning, and will treat all v2+ versions without a go.mod module declaration as incompatible with these systems (effectively treating it as a v0.0.0 version).

(I brought this up in the #dcrdata:decred.org Matrix room earlier today, but with the Slack and bridge issues, I don't know if was seen.)

**Comment by chappjc** [comment]
I did see the slack message, but this issue description is very informative.  Thanks.

I have tagged v2.0.4 and v2.1.2 so the maximum semver tags should be relatively recent.  Within a couple weeks we should have v3.0.0 tagged as well.

**Comment by jrick** [comment]
Thanks!
