### ISSUE TITLE
Insight API /status endpoint

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#638]
This is the last important endpoint that needs to be implemented.  *HIGH PRIORITY*

/sync

**Comment by chappjc** [comment]
When this closes, so will https://github.com/decred/dcrdata/issues/400

**Comment by papacarp** [comment]
Hi @chappjc i'm happy to close this out.  We have some code somewhere from @SeaLightHouse that I think never got tested or integrated.  I'll pull it up now and get a PR in
