### ISSUE TITLE
Address page feedback

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#639]
Feedback for this view: https://beta.dcrdata.org/address/Dcur2mcGjmENx4DhNqDctW5wJCVyT3Qeqkx (footer says v3.0.0-pre).

* make font size of the address a bit bigger
  * right now "Address" label is bigger than the address below it
  * maybe remove "Address" label alltogether?
* right-align Confirms column
* right-align Age column
* tx range label: add "showing" so it reads "showing 1-20 of 18,640 transactions"
* tx range label: use en dash instead of em dash (somehow it looks better to me)
* move Type and Page Size controls to the top
  * depending on page size, varied amount of scrolling is necessary to reach those controls, which might be annoying. imo "controls" that control view must be on top and not jump depending on content
* the List/Charts toggle and all other chart widgets are of different style (skin) than the Previous/Next buttons (the latter look better to me)
* place List/Charts toggle after (below) History title
  * logically they are both ways to view the history
* add some info to explain All/Credits/Debits/Merged Debits view modes
* vertically align column header labels to the top, when they multiline switch to multiline mode due to wrapping
* Age and Size columns have some weird wrapping even when there is enough width
  * this is the case when js is enabled, when js is disabled Age is blank and does not cause wrapping
* make Total Unspent bold but same height as the others
  * subjectively, text of varied ("jumping") height is hard to read

![address-page-wrapping](https://user-images.githubusercontent.com/24484727/44669441-69240600-aa0f-11e8-820d-bf2a5a79e3da.png)

**Comment by dmigwi** [comment]
@xaur Your dcrdata view looks very much different from what I have, what device are you using? laptop or desktop?

**Comment by chappjc** [comment]
Looks like the CSS is not being applied.  I forget why, but with JS disabled/blocked that happens.

**Comment by xaur** [comment]
Correct, I disabled JS, web fonts and some other stuff.

**Comment by gozart1** [comment]
Just a heads up, I'm finally getting into doing a pass on this. Will be making incremental PR's, so if others want to participate in working on the presentation of the address page we can use this issue to coordinate. 

I'm starting with some general html/css to address some minor layout alignment issues and make the buttons look a bit more fitting with the decred theme.

**Comment by chappjc** [comment]
The address page redesign is complete, so if there are issues there new issues may be created.
