### ISSUE TITLE
address page, Highlight corresponding txid on hover over

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#642]
Currently one can read the link of a 'source' or 'spent' link on the address page, and then look to find the matching txid in the table list. This could be automated for the user with JS by automatically highlighting the corresponding row with the matching txid when hovering over a source or spent link.

**Comment by chappjc** [comment]
Absolutely, even a "pulse" would be good.

The relevant information or output could be indicated on the url with an #anchor, similar to how insight does this.

**Comment by chappjc** [comment]
Sorry I responded on the PR by accident: https://github.com/decred/dcrdata/pull/665

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/696
