### ISSUE TITLE
Chain Params page feedback

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#649]
Feedback for https://explorer.dcrdata.org/parameters, footer says v2.1.2+release.

* Page and tab title: "Decred ChainParams" -> "Decred Chain Parameters"
* first label: "MainNet Parameters [github](https://github.com/decred/dcrd/blob/master/chaincfg/params.go)" -> "Parameters for Decred **mainnet** as declared in chaincfg/params.go ([github](https://github.com/decred/dcrd/blob/master/chaincfg/params.go))".
  * Anyone agrees "MainNet" is ugly?
* Left-aligned first column may look better, worth trying.
* "TicketPoolSize 8192 (40960 actual)" please explain in Description column
* Both PubKeyHashAddrID and PKHEdwardsAddrID have "P2PKH address prefix" in description, while PKHSchnorrAddrID adds the detail about Schnorr

**Comment by chappjc** [comment]
Yeah, "MainNet" is ugly.

**Comment by chappjc** [comment]
bump @McEdward

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/795.
