### ISSUE TITLE
single data point charts hide the point

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#656]
With only one data point, the chart looks empty, but the one data point is on/under the y-axis.

![image](https://user-images.githubusercontent.com/9373513/44931922-efe72480-ad28-11e8-8a32-3a4e785aa652.png)

**Comment by chappjc** [comment]
@dmigwi Not urgent, but I've assigned you to look into this.  Thanks.

**Comment by dmigwi** [comment]
Cool

**Comment by chappjc** [comment]
resolved by https://github.com/decred/dcrdata/pull/798
