### ISSUE TITLE
Low priority - Header element symbol update.

### ISSUE THREAD

**Issue by saender** [decred/dcrdata#670]
Header element Decred symbol @ top-left should be replaced w newer one:
 
<img width="665" alt="screen shot 2018-09-07 at 20 29 16" src="https://user-images.githubusercontent.com/29069168/45233915-ea677c80-b2dc-11e8-9349-e78e02d686a0.png">

Asset:
[decred-symbol-positive.svg.zip](https://github.com/decred/dcrdata/files/2361956/decred-symbol-positive.svg.zip)

**Comment by dmigwi** [comment]
@raedah recommends that we use this [Icon](https://user-images.githubusercontent.com/33739891/43585683-b66fafee-9633-11e8-8594-03c325a595c6.png) for the logo as shown here #586.

I have requested @DZ to help us convert all the Icons in the mockup to svg format.

**Comment by denyszayets** [comment]
@dmigwi attached SVG files and updated DCR logo
[svg files.zip](https://github.com/decred/dcrdata/files/2379391/svg.files.zip)

**Comment by chappjc** [comment]
Thanks for the updated package.

Closing this issue in favor of https://github.com/decred/dcrdata/pull/660, which will include the symbol update.
