### ISSUE TITLE
txfee charts

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#671]
This is more for some point in the future when txfee's become more relevant. Below are links to other txfee views from other projects.

https://github.com/jhoenicke/mempool

https://jochen-hoenicke.de/queue/#2h

https://whatthefee.io/

**Comment by chappjc** [comment]
I believe this is resolved at https://dcrdata.decred.org/charts?chart=fees&zoom=j9wi2vke-k29no5c0&bin=day&axis=time
Although fees of current mempool could be characterized better by https://dcrdata.decred.org/mempool.  Related: https://github.com/decred/dcrdata/issues/1251
