### ISSUE TITLE
correct MaximumBlockSize is missing from /parameters

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#678]
MaximumBlockSizes
https://github.com/decred/dcrd/blob/566bb6625b83738cb97ab826d5d77e862d44e92c/chaincfg/mainnetparams.go#L33

**Comment by chappjc** [comment]
This issue should remain open until https://github.com/decred/dcrd/pull/1479 is merged, and dcrdata is updated to use dcrd's new `getblockchaininfo` RPC, which will provide the correct block size.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/923
