### ISSUE TITLE
Add financial metrics and hashrate

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdata#711]
Adding the USD and BTC price of DCR as well as market capitalization data to the main page would be a good enhancement, and put us on par with other widely used sites that offer overviews of Decred.

Having the hashrate displayed on the main page is also useful `dcrctl getnetworkhashps`.

Two possible API endpoints for financial data:

https://api.coinmarketcap.com/v2/ticker/1168/?convert=BTC

https://api.coingecko.com/api/v3/coins/decred

**Comment by xaur** [comment]
That obviously requires a feature to track things external to Decred blockchain, such as a trusted price oracle.

But if this happens, it would open possibilities to implement multiple useful features.

The chart showing USD equivalent locked in PoS would be interesting: https://twitter.com/ImacallyouJawdy/status/1040656621465088001

**Comment by chappjc** [comment]
It's reasonable to have the ability to (optionally) display such off-chain data.

However, the thinking presently is this should not be gathered directly by dcrdata. 
 https://github.com/raedahgroup/dcrextdata

**Comment by xaur** [comment]
Are the metrics already available to the end user on some page(s)?

**Comment by buck54321** [comment]
@xaur They are available on the homepage on alpha, as well as through the API. Check out 

```
https://alpha.dcrdata.org/api/exchanges?indent=1
```
Or if you prefer a different currency, find the three digit currency code on 

```
https://alpha.dcrdata.org/api/exchanges/codes?indent=1
```
and request in your chosen base currency with e.g.

```
https://alpha.dcrdata.org/api/exchanges?indent=1&code=EUR
```

**Comment by xaur** [comment]
Thanks, seeing it at https://alpha.dcrdata.org/ . New UI looks great!
