### ISSUE TITLE
Reverse Tab Nabbing

### ISSUE THREAD

**Issue by degeri** [decred/dcrdata#713]
Since we are using "_blank" in our href links it opens up the site to reverse tabnabbing attacks.

This is not a critical issue as the links are static and an attacker needs to have compromised github.com to affect the site but its recommended that we fix this.  

All the issue links seem to be in https://github.com/decred/dcrdata/blob/master/views/extras.tmpl 

References:
https://www.owasp.org/index.php/Reverse_Tabnabbing
https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet#Tabnabbing
https://mathiasbynens.github.io/rel-noopener/
https://techblog.topdesk.com/security/developers-need-know-reverse-tabnabbing/

**Comment by degeri** [comment]
I'll work on this.

**Comment by chappjc** [comment]
Great @degeri!  Assigned.

**Comment by chappjc** [comment]
@degeri Were you still planning to work on this?  Since it's a security issue, it should probably be handled asap.

**Comment by degeri** [comment]
Done https://github.com/decred/dcrdata/pull/735 . Sorry for the delay.
