### ISSUE TITLE
Add network hashrate chart

### ISSUE THREAD

**Issue by jzbz** [decred/dcrdata#723]
Currently https://explorer.dcrdata.org/charts has PoW difficulty but not network hashrate. Having the latter would be useful as well.

**Comment by chappjc** [comment]
I started looking into this today.  We have a CalculateHashRate function that does the computation based on difficulty and target block time.  However, the implementation in dcrd's `getnetworkhashps` is very different, accumulating work over a variable period of blocks. The hander is defined here: https://github.com/decred/dcrd/blob/7e3dfb21974681090ad703c2350fe8146f14aa08/rpcserver.go#L3154

**Comment by xaur** [comment]
Hashrate will be derived solely from chain data, not using anything that pools report -- correct?

**Comment by chappjc** [comment]
Absolutely.  Only based on work done on the blockchain over a given period

**Comment by oregonisaac** [comment]
Ping: suggesting we move forward with adding current hash rate based on the block difficulty and the default past 120 (or some other stated number) blocks using RPCs in dcrd.

**Comment by chappjc** [comment]
@buck54321 has a proper solution underway

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/808
