### ISSUE TITLE
include chainwork in relevant API responses

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#744]
From @davecgh in Slack:
> Between the `getblockchaininfo` RPC and https://github.com/decred/dcrd/pull/1498 it's now possible to query the `chainwork` which is the cumulative total work of the chain up to that point (e.g. the total number of expected hashes needed to produce the chain up to that block).  I think it would be useful to add this to dcrdata.

Where:
1. The response for a block request.
2. Charts (chainwork over time).
3. Wherever else we return blockchain status, etc.

**Comment by buck54321** [comment]
I'd love to work on this. Are there any guidelines about how quickly changes in dcrd can be used in dcrdata?

**Comment by chappjc** [comment]
Regarding synchronize releases, we're not attempting to do that.  We should feel free to use new features in dcrd master right away.  I may just exclude such changes from our release branches, but generally we require running a recent dcrd.

**Comment by buck54321** [comment]
This is closely related to #723. I'll need to add a new column to the auxiliary DB blocks table. Any objections?

**Comment by chappjc** [comment]
No objection.  blocks is relatively short, so I don't anticipate much performance or storage penalty.

**Comment by buck54321** [comment]
The first part was simple (#808), but then this got pretty deep pretty quick. It seems that `dcrd/dcrjson` types have chainwork, but `dcrd/wire` types do not. Chainwork is not stored on the blockchain, but is populated during initialization of dcrd (I think). Unfortunately, `wire.MsgBlock` is often initialized directly from the encoded block, so chainwork is not available in `wire.MsgBlock` as implemented. 

It seems like all database syncing uses the `wire` types, often via `dcrutil`. I see a few options here.

1. Rewrite everything to use the `dcrjson` types. This doesn't seem feasible.
2. An additional RPC call where necessary. This would be especially costly during `SyncChainDB`, but would cost nothing during calls to `Store`, which has a `drcjson` type available already. 
3. Try to populate the data ourselves. Work is just a function of difficulty, so you can start at the genesis block and and sum as you work up the chain. Will probably require an additional database query for some inserts, which might not be so bad. 
4. I could open an issue at dcrd to see if we can get chainwork added to `MsgBlock`.

**Comment by chappjc** [comment]
Let's go with route 4. to start.  This may just be an oversight.

But when you say `wire.MsgBlock is often initialized directly from the encoded block, so chainwork is not available in wire.MsgBlock as implemented`, to which parts of the code are you referring.

**Comment by buck54321** [comment]
`dcrdata/rpcutils.GetBlock -> dcrd/rpcclient.GetBlock -> rpclient.GetBlockAsync` requests the block unencoded via 

`dcrjson.NewGetBlockCmd(hash, dcrjson.Bool(false), nil)`

and then decodes it via

`rpclient.FutureGetBlockResult.Receive -> wire.MsgBlock.Deserialize`

**Comment by chappjc** [comment]
Well, I get jrick's comment on the dcrd issue.  Given the purpose of the `wire` package, it doesn't make a lot of sense to have it in the `MsgBlock` struct.

If we need to go with a second RPC, we could also go with `getblockheaderverbose`.  :(

**Comment by buck54321** [comment]
It was worth a shot. Any guesses on what an additional RPC call will add to the sync time?

Luckily blocks stored via `BlockDataSaver.Store` already have the info, so no real penalty there.

**Comment by chappjc** [comment]
depends on the RPC, but it should be pretty darn fast.

**Comment by davecgh** [comment]
`getblockheaderverbose` is near instant, and it's necessarily linear time.  It won't add any appreciable time, especially if using websockets.
