### ISSUE TITLE
Ticket Price Windows feedback

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#763]
Feedback on [latest screenshot](https://github.com/decred/dcrdata/pull/750#issuecomment-433200621) of the new Ticket Price Windows page

* typo in description: "are adjusted every 144 blocks or on Mainnet" -- remove 'or', use lowercase 'mainnet'
* all numeric columns and Age would look better right-aligned
* use `en dash` or hyphen without spaces in Page size block: `1–20 of 1,989` (source: [wikipedia](https://en.wikipedia.org/wiki/Dash#Ranges_of_values)).. or even hyphen with spaces, but in any case em dash is too large imo
* consider thousand separator in Transactions column

cc @dmigwi

![](https://user-images.githubusercontent.com/22055953/47529387-55cad500-d8b0-11e8-8cd0-883120313ce0.png)

**Comment by xaur** [comment]
Something else to consider is the order of pagination buttons. As we go back in history, to we "move to the left" or "to the right"? i.e. `[Older Newer]` or `[Newer Older]`?

**Comment by dmigwi** [comment]
Sure, @xaur  The new pagination arrangement would be used as the default all through dcrdata.

**Comment by chappjc** [comment]
resolved by https://github.com/decred/dcrdata/pull/767
