### ISSUE TITLE
Header logo needs update.

### ISSUE THREAD

**Issue by saender** [decred/dcrdata#764]
![oldlogo](https://user-images.githubusercontent.com/29069168/47566792-7426e400-d935-11e8-87f7-134776cad10b.jpg)

New logo symbol can be found at:
https://github.com/decred/dcrdesign/releases -> Identity -> Logo package -> 
https://github.com/decred/dcrdesign/files/2160933/decred.-.logo.package.zip
-> Decred - Logo Package -> RGB -> Symbol

**Comment by chappjc** [comment]
I believe this has already been updated.  See https://alpha.dcrdata.org/

However, it's not a drop-in replacement.  Making it look OK in night mode will take some additional work.  @gozart1 ^

**Comment by saender** [comment]
Utility sites should have monotone logo/symbol and mentioned logo package contains both negative and positive versions for light or dark theme.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/770
