### ISSUE TITLE
Keep new style (header, footer, logo, colors) on /next home

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#765]
Until the new styles are polished, we should keep the previous (3.0) styles the same on most pages.  The style changes should only be applied to /nexthome and other newer pages that we are simply testing.

As we move through the 3.x series, the styles should stay the same.  When the styles are polished properly, that will be 4.0 and they can be applied to all pages (that will be when /nexthome takes over as the default home page).

This primarily includes:
- old header style (size and colors)
- old monochrome logo

Having night mode colors and testnet colors completely screw things up is the main issue.

**Comment by dmigwi** [comment]
I ended up fixing the nexthome page night mode and all seems well.
