### ISSUE TITLE
nexthome.css is a mess, is overwriting core bootstrap classes

### ISSUE THREAD

**Issue by gozart1** [decred/dcrdata#782]
Right now nexthome.css is overwriting various bootstrap layout classes and this is a huge anti pattern.
https://github.com/decred/dcrdata/blob/master/public/css/nexthome.css#L509

Please, if you want to do front end work, learn what bootstrap is and how to use it. Especially the grid and positioning system.
https://css-tricks.com/ is a great resource for general css knowledge.
In general though, we should lean heavily on boostrap as it's a battle tested approach that solves countless cross browser issues.

I'm not sure who authored that nexthome.css code, I think @dmigwi just ported it from someone somewhere outside this repo. But it needs to be cleaned up.

**Comment by chappjc** [comment]
If it is at all possible to keep nexthome.css from loading except on /nexthome, let's do that.

In order to have a stable 3.1, we need to have things almost the same as in 3.0, perhaps with an updated logo and some other tweaks, but no major redesign stuff.

@dmigwi I assigned you to have a look at addressing the issues addressed here.  I think this may be the time to step back from coding and look closer at bootstrap best practices so we are pointing in the right direction after this.

**Comment by dmigwi** [comment]
@gozart1 Thanks for raising the above concerns, I had not given browser compatibility a serious thought till now. The design team(in @raedah's group) came up with the nexthome's page css so to as hasten the feature implementation.

@chappjc We shall do that ASAP.

**Comment by chappjc** [comment]
Is there a repo to report such issues?  https://github.com/raedahgroup/design seems to be empty.

**Comment by dmigwi** [comment]
The code is on a bitbucket repo https://bitbucket.org/vikkbehal/decred/src/master/

**Comment by itswisdomagain** [comment]
> If it is at all possible to keep nexthome.css from loading except on /nexthome, let's do that.

I had this thought sometime ago, even the style name suggested the style should only apply to /nexthome. I tried to move the linking from extras.tmpl to nexthome.tmpl and other pages were affected so I left things as they were.

I strongly agree with linking nexthome.css to nexthome.tmpl only and then cleaning up nexthome.css to keep only styles that affect /nexthome; but how to fix the styling issues that will unearth in other pages after doing this is what I have little idea of. Before nexthome.css, did not every other page have the styles required to make them look the way they should?

**Comment by chappjc** [comment]
I'm sure every other page had what it needed.  They should again.

**Comment by chappjc** [comment]
I believe this was resolved with several recent PRs, ending with https://github.com/decred/dcrdata/pull/718.  Please close if this appears to be correct.

**Comment by chappjc** [comment]
It looks like there are still overridden bootstrap classes: https://github.com/decred/dcrdata/blob/b70b287c11759dbd104ad5af9fcc8b88bc4203ae/public/css/nexthome.css#L488-L541

**Comment by gozart1** [comment]
Indeed, all layout overrides should be removed.
**Along with any styles related to header and footer.** 
I think I mentioned this multiple times in the review.
But got tired of repeating myself, my bad, should not have Ok'd the review.

If there is a sensible global override, like changing a button color.
It can be done here (for now):
https://github.com/decred/dcrdata/blob/master/public/css/main.css#L931

I'm working on porting us over to webpack and once that's in, we can start using scss variables to theme boostrap the correct way. I'm planning to keep the initial PR will be scoped to JS only though. https://github.com/decred/dcrdata/pull/805

**Comment by chappjc** [comment]
@gozart1 nexthome.css is in OK shape now, right?  Feel free to close this issue if that's correct.
