### ISSUE TITLE
Return the current network on /status

### ISSUE THREAD

**Issue by matheusd** [decred/dcrdata#800]
This could either be a the name ("mainnet"/"testnet"/"simnet") or the network constant or both.

This would allow a client to verify it's connecting to a dcrdata instance that belongs to the correct network when using a user-provided domain.

My suggestion is to implement this on the /status api call because it seems the most logical place for this, but it could be anywhere really.

**Comment by chappjc** [comment]
Resolved by PR https://github.com/decred/dcrdata/pull/801
