### ISSUE TITLE
Return the raw (hex) pkscript in /tx/* apis

### ISSUE THREAD

**Issue by matheusd** [decred/dcrdata#802]
In addition to returning the decoded output pkscript, it would be useful to have the raw pkscript in raw format in the /tx endpoints (eg: /tx/T, /txs, etc). Basically, return this in the `vout` api struct.

**Comment by chappjc** [comment]
Sure, we can add a `"hex"` after the `"asm"` for each vout.  Is this what you have in mind?

**Comment by chappjc** [comment]
Resolved by PR https://github.com/decred/dcrdata/pull/803
