### ISSUE TITLE
Block connected signal causes javascript error on /ticketpool

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdata#826]
This is an issue in v3.1.0-rc1. When the `newblock` websocket signal is received by the ticketpool controller, an error occurs looking for the `ticket_pool_data.Mempool` property.

**Comment by chappjc** [comment]
Could you have a quick look at the 3.1-stable port at https://github.com/decred/dcrdata/pull/842?

**Comment by chappjc** [comment]
tACK.  Verified that the /ticketpool websocket events are working, as are the key bindings.  Just one comment about the hot keys I had is that it would be intuitive for the the up/down arrows to have the same function as the left/right, at least in most cases such as rows in a table.  Thoughts?

**Comment by chappjc** [comment]
Actually I noticed a "Violation" in the browser console:

```
12 [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
```

There are 12 such messages where `<some>` is either `touchstart` or `touchmove`.  The `<URL>` is https://www.chromestatus.com/feature/5745543795965952
