### ISSUE TITLE
AddressMetrics runs too slowly

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdata#835]
Very long load times (~10s) are observed on the `/address` page for the project treasury, and presumably any address with a lot of transactions. The majority of load time is spent on `dcrpg.AddressMetrics` in four queries of the following form

```
SELECT COUNT(DISTINCT date_trunc('year', block_time)) FROM addresses WHERE address=$1;
SELECT COUNT(DISTINCT date_trunc('month', block_time)) FROM addresses WHERE address=$1;
SELECT COUNT(DISTINCT date_trunc('week', block_time)) FROM addresses WHERE address=$1;
SELECT COUNT(DISTINCT date_trunc('day', block_time)) FROM addresses WHERE address=$1;
```

The values  collected here are used to determine whether the grouping selection button will be displayed on `/address`. See [here](https://github.com/decred/dcrdata/blob/9e23b9a8e6b5f93dacfe1de1822b29c2c81bde8a/public/js/controllers/address_controller.js#L334). 

It appears that the counts retrieved are used as essentially boolean values. I believe the complexity of the queries could be reduced substantially by simply looking at the first and last transaction times for a given address and disabling buttons based on the difference, e.g. if the difference is > 1 week, show the week button.

@dmigwi #798

**Comment by dmigwi** [comment]
> I believe the complexity of the queries could be reduced substantially by simply looking at the first and last transaction times for a given address and disabling buttons based on the difference

This will not always work especially for addresses with very few transactions where the first transaction was made like years ago.
The above implementation also fixes the bug that you've highlighted there and I don't using approximations will even work better than the actual value, you will have introduced other bugs.

1. One of the solution would be to block the queries from running on consecutive times if the address remains constant over a certain period of time.
2. You could also create a cache with the data for the above queries for all the common addresses normally used.
3. And finally graphs db could be faster than pg but I don't think this is worth the hustle of moving dcrdata from psql to an appropriate graph db.

**Comment by chappjc** [comment]
As @buck54321 points out, the JS only checks if the count<2, so it seems the result would be the same if you checked the oldest and newest times, and decided if they are in the same year/month/week/day.

**Comment by buck54321** [comment]
Also, since the elements that use the `AddressMetrics` data are not displayed by default, I would also recommend we move the metrics collection to an AJAX call. This would allow the page to be displayed much much faster, and the delay associated with metrics collection would only be seen if the user switched to the graphs tab before the AJAX call had completed. This is not to say that the metrics collection doesn't need to be faster. 10 seconds is too long.

**Comment by buck54321** [comment]
Complete with #845
