### ISSUE TITLE
Mempool page styling issues

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdata#838]
There a few issues on the mempool page that might warrant attention. 

![image](https://user-images.githubusercontent.com/6109680/48984690-b2dec400-f0c4-11e8-8ce2-3d6949dc302a.png)

I actually don't mind the empty space, and it makes resizing easier, but I thought I'd point it out.

**Comment by lte13** [comment]
Im giving this a try

**Comment by buck54321** [comment]
@chappjc and @lte13 This should probably have been closed when #982 was merged. I think this is resolved now.

**Comment by chappjc** [comment]
Agreed. The mempool page is entirely different now, and quite nice IMO.
