### ISSUE TITLE
Need to remove all inline JS, starting with this

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#841]
https://github.com/decred/dcrdata/blob/db8e600af08c210c88d0830001a71c2637247a93/views/charts.tmpl#L140-L142

Using Go's html template engine to set JSON data in inline javascript.  We need to remove that anyway possible.

_Originally posted by @chappjc in https://github.com/decred/dcrdata/pull/832#issuecomment-442087283_

Ref 1: https://github.com/decred/dcrdata/pull/463#pullrequestreview-129342817
Ref 2: https://github.com/decred/dcrdata/pull/463#issuecomment-397712158

This facilitates proper CSP: https://github.com/decred/dcrdata/pull/832

**Comment by buck54321** [comment]
Closing with #843
