### ISSUE TITLE
Voting agenda chart (alpha) shows incorrect dates

### ISSUE THREAD

**Issue by oregonisaac** [decred/dcrdata#858]
Erroneous 2017-04-26 date showing:
![image](https://user-images.githubusercontent.com/4402603/49539102-c8e94300-f881-11e8-83dc-cfa7754d5e76.png)

**Comment by chappjc** [comment]
@dmigwi Would you mind taking a brief look at this?  I'm not intimately familiar with the agendadb operation.

**Comment by dmigwi** [comment]
@chappjc Sure. Is there a way confirm the accurate dates?

**Comment by dmigwi** [comment]
I used https://www.epochconverter.com/ to convert the starttime and the expiretime of `sdiffalgorithm` agenda to human readable format and got exactly what is said to be incorrect.
**starttime**
![screenshot from 2018-12-08 00-27-45](https://user-images.githubusercontent.com/22055953/49673696-63af7080-fa80-11e8-991a-72add9abb6fa.png)

**expiretime**
![screenshot from 2018-12-08 00-21-51](https://user-images.githubusercontent.com/22055953/49673688-5e522600-fa80-11e8-9d20-c32fbfd485eb.png)

@oregonisaac Can you add more details about what is incorrect and how to confirm the correct time?

**Comment by chappjc** [comment]
Thanks for confirming.  I got the same thing when I checked it out.

**Comment by chappjc** [comment]
Oh, lol, it says 2017 instead of 2018!

**Comment by chappjc** [comment]
It seem to be correct, so closing.
