### ISSUE TITLE
Transaction page block field doesn't update.

### ISSUE THREAD

**Issue by ZeroASIC** [decred/dcrdata#906]
The block field doesn't update from pending to the block number when it should.  At 0 confirmations it says 'Pending'  but when it goes to 1 confirmation it should update.  When I hit F5 it reloaded with block 304781.
![screenshot_2018-12-28_15-46-54](https://user-images.githubusercontent.com/4195716/50529120-594d2900-0ab8-11e9-8291-f03a62209982.png)

**Comment by buck54321** [comment]
@ZeroASIC Any interest in this one? Otherwise, I'll grab it.

**Comment by ZeroASIC** [comment]
> @ZeroASIC Any interest in this one? Otherwise, I'll grab it.

I've actually been looking at it the past day, but I'm not exactly sure what to do.  Maybe you can do it and I can follow along.  I know it needs an update to tx.tmpl around line 342 and something in tx_controller.js, but I'm not sure if the correct data is already available.

**Comment by buck54321** [comment]
Sure thing. Stimulus makes it pretty quick. I'll probably push it later tonight.
