### ISSUE TITLE
Rename /rejects to /disapproved

### ISSUE THREAD

**Issue by xaur** [decred/dcrdata#919]
"Disapproved blocks" seems to have gained support in discussions to refer to blocks that were voted against by PoS voters. The term 'disapproved' is even used on the current [/rejects](https://explorer.dcrdata.org/rejects) page.

I suggest to change the path too to avoid confusion. The blocks are not _rejected_ by the network -- they are accepted as being valid by consensus, they extend the chain and only lose regular transactions.

**Comment by chappjc** [comment]
No objection to the proposed changes.  I think I chose rejects since reject is an antonym of approve.  On the other hand, valid/invalid are how I think of consensus rules deciding on blocks.  However disapproved is clearer that rejects.
