### ISSUE TITLE
zoom broken for /charts with blocks in x axis

### ISSUE THREAD

**Issue by gozart1** [decred/dcrdata#928]
Zoom logic used to operate on blocks and dates via some rudimentary normalization code that got removed here:
https://github.com/decred/dcrdata/commit/6232a0f61648aa3a9ab6e865459da6672dca8a79#diff-d25f91f9067a971563389702ed3e5679L357

So at the moment, zoom is broken when the x axis is blocks. Might be something simple, @buck54321 can you spot the issue?

On another note, `validateZoom` should probably be renamed to `updateZoom` as it's doing a lot more than validation.

**Comment by buck54321** [comment]
Looks like I didn't get the scaling right. I'll push a fix today. 

The change to text values was to make the implementation consistent with the zoom buttons on the address page, which enables some simplification of the `Zoom` class.

**Comment by buck54321** [comment]
Resolved by #930
