### ISSUE TITLE
DB scanner and error checker

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#944]
It would be valuable to have a tool to scan DB tables and check for issues like missing or invalid data, and attempt recovery.  Assigning myself.

**Comment by chappjc** [comment]
Moving to 4.1

**Comment by dmigwi** [comment]
Great task!. This means that you would need to create/maintain a source of truth that will be used to compare data in the dbs. This tool, could be set to run those late or early hours when the traffic to dcrdata to quite low.

**Comment by dmigwi** [comment]
This task could get fixed in the process https://github.com/decred/dcrdata/issues/591

**Comment by chappjc** [comment]
I see this as a separate task from https://github.com/decred/dcrdata/issues/591.  I have a number of checks in mind, most of which will verify the assumptions we make about the data relationships.  For example,

1. In SQLite, missing data points can happen due to the database is locked error.  Checking data at each height can help identify issues, an perhaps repair them.
2. In PostgreSQL, verify that any row in the `addresses` table that is "spending" will have `matching_tx_hash` set.
3. In PG, verify that chain work is monotonically increasing w.r.t. height.
4. In PG, check address spend information.
...

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1429, but it can be expanded.
