### ISSUE TITLE
add unparam back into golangci-lint linters

### ISSUE THREAD

**Issue by chappjc** [decred/dcrdata#956]
golangci-lint and/or unparam was updated and now it catches legit unparam candidates.  They need to be addressed, and unparam added back into the golangci-lint CI linters.

**Comment by mvdan** [comment]
Sure, that makes sense. There were a few of these false positive bugs recently, but I fixed a lot of them a few days ago. Have you tried the latest version from the master branch at https://github.com/mvdan/unparam? I might have missed a few edge cases.

**Comment by chappjc** [comment]
No, but I will.  I'm using `golangci-lint` master from Friday, which seems to be pinned to [unparam 20181201214637-68701730a1d7](https://github.com/golangci/golangci-lint/blob/7b2421d55194c9dc385eff7720a037aa9244ca3c/go.mod#L65).

**Comment by mvdan** [comment]
Yep - let me know how that goes. #367 tracks golangci-lint's updating of the tool.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/957, although the `//nolint:unparam` comments can be removed when golangci-lint merges https://github.com/golangci/golangci-lint/pull/381 and we then update our deps.
