### ISSUE TITLE
create chart for % of coin supply staked

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#996]

**Comment by xaur** [comment]
That would help me a lot for Decred Journal. dcred.eu/powStats has incorrect chart of locked %. Someone recommended a replacement at [charts.dcr.farm](https://charts.dcr.farm/) -- need to check it out but I already see it wants too much perms. In any case, having this on dcrdata would be great.

**Comment by xaur** [comment]
charts.dcr.farm doesn't open anymore for me. dcred.eu has wrong % numbers.

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/1355
