### ISSUE TITLE
BlockChain Size chart should be Blockchain Size

### ISSUE THREAD

**Issue by raedah** [decred/dcrdata#998]
lower case C in Blockchain

**Comment by dmigwi** [comment]
Fixed here https://github.com/decred/dcrdata/commit/597b775aa2ba08a0fb231eddb0fd1f83a77996b9#diff-1913d14c3d3efcab9e79e18096104427R28

**Comment by chappjc** [comment]
Resolved by https://github.com/decred/dcrdata/pull/980
